/* Generated by c/tools/gen_clinical_context.py -- do not edit by hand.
 * Source: genetic_health/clinical_context.py
 */

#include "gh_clinical_context.h"

#include <stddef.h>

static const char *const cc_ACE_high_implications[] = {
    "Increased hypertension risk",
    "May confer advantage in power/sprint athletics",
    "Good response expected to ACE inhibitors",
};
static const char *const cc_ACE_high_actions[] = {
    "Blood pressure monitoring essential",
    "ACE inhibitors (lisinopril, enalapril) likely very effective if needed",
    "Potassium-rich diet supports blood pressure",
};
static const char *const cc_ACE_high_interactions[] = {
    "Synergizes with AGTR1 and AGT variants for BP risk",
};

static const char *const cc_ACTN3_mixed_implications[] = {
    "Versatile muscle fiber composition",
    "Can develop both power and endurance capacity",
    "Neither extreme sprinter nor ultra-endurance genotype",
};
static const char *const cc_ACTN3_mixed_actions[] = {
    "Train for both power and endurance based on goals",
    "Respond well to varied training programs",
    "Can optimize for either direction with proper training",
};

static const char *const cc_ADH1B_slow_implications[] = {
    "Alcohol effects last longer",
    "May feel effects at lower doses",
    "Slower acetaldehyde production (not the \"flush\" gene)",
};
static const char *const cc_ADH1B_slow_actions[] = {
    "Moderate alcohol consumption appropriate",
    "Effects may persist longer - factor into timing",
    "Space drinks and stay hydrated",
};
static const char *const cc_ADH1B_slow_interactions[] = {
    "ALDH2 affects second step (acetaldehyde clearance)",
};

static const char *const cc_ADORA2A_anxiety_prone_implications[] = {
    "More likely to experience jitteriness, anxiety, or panic from caffeine",
    "May be more sensitive to sleep disruption from caffeine",
};
static const char *const cc_ADORA2A_anxiety_prone_actions[] = {
    "Consider lower caffeine doses or slower-release forms",
    "Pair caffeine with L-theanine (green tea naturally has this)",
    "Matcha or green tea may be better tolerated than coffee",
    "Consider caffeine alternatives: yerba mate, guayusa",
};
static const char *const cc_ADORA2A_anxiety_prone_interactions[] = {
    "Compounds with slow COMT for stress sensitivity",
};

static const char *const cc_ADORA2A_lower_sensitivity_implications[] = {
    "Less likely to experience anxiety from caffeine",
    "May tolerate higher doses without jitteriness",
};
static const char *const cc_ADORA2A_lower_sensitivity_actions[] = {
    "Can likely enjoy caffeine without anxiety issues",
    "Still respect timing for sleep quality",
};

static const char *const cc_ADRB2_gly16_implications[] = {
    "Better fat mobilization during exercise",
    "Enhanced response to beta-agonists (bronchodilators)",
};
static const char *const cc_ADRB2_gly16_actions[] = {
    "May see good fat loss response to exercise",
    "Cardio and HIIT can be particularly effective for body composition",
};

static const char *const cc_AGT_increased_implications[] = {
    "Slightly elevated blood pressure risk",
    "Contributes to overall cardiovascular profile",
};
static const char *const cc_AGT_increased_actions[] = {
    "Part of overall BP monitoring strategy",
    "Responds to general cardiovascular lifestyle measures",
};
static const char *const cc_AGT_increased_interactions[] = {
    "Additive with ACE and AGTR1 variants",
};

static const char *const cc_AGTR1_increased_implications[] = {
    "Higher risk of developing hypertension",
    "May have enhanced response to angiotensin receptor blockers (ARBs)",
};
static const char *const cc_AGTR1_increased_actions[] = {
    "Regular blood pressure monitoring",
    "Sodium restriction particularly beneficial",
    "ARBs (losartan, valsartan) may be especially effective if BP medication needed",
};
static const char *const cc_AGTR1_increased_interactions[] = {
    "Compounds with ACE and AGT variants",
};

static const char *const cc_APOA2_sensitive_implications[] = {
    "Saturated fat intake more strongly linked to weight gain for you",
    "Limiting saturated fat may be more impactful than for others",
};
static const char *const cc_APOA2_sensitive_actions[] = {
    "Limit saturated fat to <7% of calories",
    "Replace with unsaturated fats (olive oil, nuts, avocado)",
    "Minimize: butter, fatty red meat, full-fat dairy, coconut oil",
    "Prioritize: olive oil, fatty fish, nuts, avocados",
};

static const char *const cc_ARNTL_significantly_altered_implications[] = {
    "May have less robust circadian rhythm",
    "Potentially more susceptible to jet lag, shift work effects",
    "Sleep timing may be less consistent",
};
static const char *const cc_ARNTL_significantly_altered_actions[] = {
    "Strong light exposure in morning (10,000 lux or sunlight)",
    "Consistent sleep/wake times, even weekends",
    "Blue light reduction in evening",
    "Consider melatonin 0.5-1mg 30-60 min before bed if needed",
    "Keep bedroom cool, dark, quiet",
};

static const char *const cc_BCMO1_reduced_implications[] = {
    "Plant carotenoids (carrots, sweet potatoes) less efficiently converted to vitamin A",
    "May benefit from preformed vitamin A sources",
};
static const char *const cc_BCMO1_reduced_actions[] = {
    "Include preformed vitamin A: liver, eggs, dairy, fatty fish",
    "Don't rely solely on beta-carotene for vitamin A needs",
    "Still consume carotenoid-rich foods for other benefits (antioxidant)",
};

static const char *const cc_CETP_favorable_implications[] = {
    "Favorable lipid profile tendency",
    "Associated with exceptional longevity in studies",
};
static const char *const cc_CETP_favorable_actions[] = {
    "This is a favorable variant",
    "Support with heart-healthy lifestyle",
};

static const char *const cc_COMT_slow_implications[] = {
    "Higher baseline dopamine - better working memory, focus in calm conditions",
    "More sensitive to stress - catecholamines accumulate faster under pressure",
    "Stimulants (caffeine, medications) have stronger, longer-lasting effects",
    "May be more prone to anxiety and rumination",
    "Can have advantages in pain tolerance",
};
static const char *const cc_COMT_slow_actions[] = {
    "Prioritize stress management: meditation, breathwork, regular exercise",
    "Use lower doses of stimulants; caffeine half-life effectively longer for you",
    "Magnesium (glycinate, 300-400mg) supports COMT function",
    "Consider adaptogens (ashwagandha, rhodiola) over stimulants for energy",
    "L-theanine may help modulate catecholamine effects",
    "Avoid combining multiple stimulants",
};
static const char *const cc_COMT_slow_interactions[] = {
    "Synergizes with caffeine metabolism genes",
    "Affects response to ADHD medications",
};

static const char *const cc_CYP1A2_intermediate_implications[] = {
    "Moderate caffeine clearance - effects last several hours",
    "Afternoon caffeine may affect sleep more than fast metabolizers",
    "Cardiovascular effects of caffeine are intermediate",
};
static const char *const cc_CYP1A2_intermediate_actions[] = {
    "Limit caffeine to morning/early afternoon (before 2pm ideally)",
    "Moderate intake (~200-300mg/day) typically well-tolerated",
    "Wait 90+ minutes after waking for first caffeine (cortisol awakening response)",
};
static const char *const cc_CYP1A2_intermediate_interactions[] = {
    "ADORA2A affects anxiety response to caffeine",
};

static const char *const cc_CYP2C19_rapid_implications[] = {
    "Faster breakdown of PPIs (may need higher doses or alternatives)",
    "Faster clopidogrel activation (actually better for this prodrug)",
    "Some antidepressants metabolized faster",
};
static const char *const cc_CYP2C19_rapid_actions[] = {
    "PPIs (omeprazole): may need higher doses or alternatives",
    "Clopidogrel: good metabolizer, likely effective",
    "Inform prescribers about CYP2C19 status",
};
static const char *const cc_CYP2C19_rapid_interactions[] = {
    "Pharmacogenomic testing reference",
};

static const char *const cc_CYP3A5_non_expressor_implications[] = {
    "Standard dosing for CYP3A4/5 substrates",
    "Tacrolimus dosing follows standard protocols",
};
static const char *const cc_CYP3A5_non_expressor_actions[] = {
    "Standard drug dosing typically appropriate",
    "CYP3A4 remains the primary metabolizer for many drugs",
};

static const char *const cc_GC_low_implications[] = {
    "Genetically predisposed to lower vitamin D status",
    "Higher supplementation needs, especially at northern latitudes",
    "May need to supplement year-round",
};
static const char *const cc_GC_low_actions[] = {
    "Supplement vitamin D3: 2,000-5,000 IU/day depending on season and sun exposure",
    "Take with fat-containing meal for absorption",
    "Test 25-OH vitamin D after 2-3 months",
    "Target blood level: 40-60 ng/mL (100-150 nmol/L)",
    "Consider vitamin K2 (MK-7) alongside D3",
};

static const char *const cc_GNB3_increased_implications[] = {
    "Increased hypertension risk",
    "May be more prone to weight gain",
    "Can affect response to certain medications",
};
static const char *const cc_GNB3_increased_actions[] = {
    "Weight management particularly important",
    "Regular blood pressure monitoring",
    "May respond differently to beta-blockers",
};
static const char *const cc_GNB3_increased_interactions[] = {
    "Compounds with other BP variants",
};

static const char *const cc_HFE_carrier_implications[] = {
    "Mild increase in iron absorption",
    "Usually not clinically significant alone",
    "Should be aware of iron accumulation over time",
};
static const char *const cc_HFE_carrier_actions[] = {
    "Periodic ferritin checks (every 1-2 years)",
    "Avoid unnecessary iron supplements",
    "Blood donation if ferritin runs high - helps regulate iron",
};
static const char *const cc_HFE_carrier_interactions[] = {
    "Compound with C282Y for hemochromatosis risk",
};

static const char *const cc_HLA_DQA1_increased_risk_implications[] = {
    "Increased risk of celiac disease (but not guaranteed)",
    "~3% of HLA-DQ2.5 carriers develop celiac disease",
    "Should be aware of celiac symptoms",
};
static const char *const cc_HLA_DQA1_increased_risk_actions[] = {
    "Know celiac symptoms: GI issues, fatigue, anemia, nutrient deficiencies",
    "If symptoms arise, get celiac antibody testing (tTG-IgA) while still eating gluten",
    "No need for preventive gluten-free diet unless symptomatic",
    "Inform healthcare providers of this risk",
};

static const char *const cc_IL6_high_implications[] = {
    "Higher baseline inflammation",
    "More pronounced inflammatory response to triggers",
    "May affect recovery, aging, chronic disease risk",
};
static const char *const cc_IL6_high_actions[] = {
    "Anti-inflammatory diet: omega-3s, colorful vegetables, low processed foods",
    "Omega-3 fatty acids (EPA/DHA): 2-3g/day",
    "Regular exercise (but don't overtrain)",
    "Adequate sleep - sleep deprivation spikes IL-6",
    "Consider curcumin, SPMs (specialized pro-resolving mediators)",
};
static const char *const cc_IL6_high_interactions[] = {
    "Affects recovery and chronic disease risk",
};

static const char *const cc_MC1R_accelerated_implications[] = {
    "May show earlier signs of skin aging (wrinkles, photoaging)",
    "Importance of sun protection heightened",
};
static const char *const cc_MC1R_accelerated_actions[] = {
    "Daily broad-spectrum SPF 30+ sunscreen",
    "Topical retinoids (tretinoin, retinol) for anti-aging",
    "Antioxidant serums (vitamin C, E)",
    "Avoid excessive sun exposure and tanning",
};

static const char *const cc_MTHFR_significantly_reduced_implications[] = {
    "Elevated homocysteine levels (cardiovascular risk marker)",
    "Reduced production of SAMe (S-adenosylmethionine), the universal methyl donor",
    "Potential impacts on neurotransmitter synthesis, DNA repair, and detoxification",
    "Folic acid from fortified foods may accumulate as unmetabolized folic acid (UMFA)",
};
static const char *const cc_MTHFR_significantly_reduced_actions[] = {
    "Use methylfolate (5-MTHF) instead of folic acid - typical dose 400-800mcg",
    "Consider methylcobalamin (methyl-B12) rather than cyanocobalamin",
    "Support with riboflavin (B2) which is a cofactor for MTHFR",
    "Monitor homocysteine levels periodically",
    "Avoid high-dose folic acid supplements and limit heavily fortified foods",
};
static const char *const cc_MTHFR_significantly_reduced_interactions[] = {
    "Synergizes with MTRR status - both impaired compounds effect",
    "COMT status affects methylation demand",
};

static const char *const cc_MTRR_significantly_reduced_implications[] = {
    "May need higher B12 intake to maintain adequate methylcobalamin levels",
    "Can compound MTHFR issues (both affect methylation)",
    "Potential neurological and cognitive effects if B12 recycling insufficient",
};
static const char *const cc_MTRR_significantly_reduced_actions[] = {
    "Use methylcobalamin or adenosylcobalamin forms of B12",
    "Consider sublingual or injectable B12 for better absorption",
    "Typical supportive dose: 1000-5000mcg methylcobalamin",
    "Check serum B12 and methylmalonic acid (MMA) for functional status",
};
static const char *const cc_MTRR_significantly_reduced_interactions[] = {
    "Compounds with MTHFR C677T",
    "Affects homocysteine pathway",
};

static const char *const cc_NAT2_intermediate_implications[] = {
    "Moderate metabolism of drugs like isoniazid, hydralazine, some sulfonamides",
    "Between slow and fast acetylator phenotypes",
};
static const char *const cc_NAT2_intermediate_actions[] = {
    "Generally standard drug dosing appropriate",
    "Inform physicians if taking NAT2-metabolized drugs",
};

static const char *const cc_OPRM1_altered_implications[] = {
    "May require different opioid dosing for pain management",
    "Altered reward response to alcohol (some studies show increased craving)",
    "Potentially different response to naltrexone treatment",
};
static const char *const cc_OPRM1_altered_actions[] = {
    "Inform anesthesiologists before surgery",
    "May need adjusted opioid dosing for adequate pain control",
    "Be aware of potentially altered alcohol reward response",
};
static const char *const cc_OPRM1_altered_interactions[] = {
    "Relevant for pain management planning",
};

static const char *const cc_PEMT_reduced_implications[] = {
    "Higher dietary choline requirement",
    "Particularly important during pregnancy (fetal brain development)",
    "May affect liver health and lipid metabolism",
};
static const char *const cc_PEMT_reduced_actions[] = {
    "Increase dietary choline: eggs (especially yolks), liver, beef, fish",
    "Consider choline supplementation: 250-500mg phosphatidylcholine or CDP-choline",
    "Ensure adequate methyl donors (folate, B12) as PEMT uses SAMe",
};
static const char *const cc_PEMT_reduced_interactions[] = {
    "Increased demand when MTHFR is impaired (SAMe dependent)",
};

static const char *const cc_SOD2_high_activity_implications[] = {
    "Efficient mitochondrial antioxidant defense",
    "Good protection against mitochondrial oxidative stress",
};
static const char *const cc_SOD2_high_activity_actions[] = {
    "This is a favorable variant - no specific intervention needed",
    "Continue supporting mitochondrial health: exercise, CoQ10, adequate sleep",
};

static const char *const cc_TP53_arg72_implications[] = {
    "Slightly less efficient programmed cell death",
    "Complex effects on cancer and aging",
};
static const char *const cc_TP53_arg72_actions[] = {
    "Standard cancer screening appropriate for age",
    "Anti-aging lifestyle: exercise, sleep, stress management, healthy diet",
};

const gh_clinical_context GH_CLINICAL_CONTEXT[] = {
    {
        .gene = "ACE",
        .status = "high",
        .mechanism = "Higher ACE activity means more conversion of angiotensin I to angiotensin II, a potent vasoconstrictor.",
        .implications = cc_ACE_high_implications,
        .nimplications = 3,
        .actions = cc_ACE_high_actions,
        .nactions = 3,
        .interactions = cc_ACE_high_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "ACTN3",
        .status = "mixed",
        .mechanism = "ACTN3 R577X affects fast-twitch muscle fiber composition. R/X (heterozygous) provides balanced fiber distribution.",
        .implications = cc_ACTN3_mixed_implications,
        .nimplications = 3,
        .actions = cc_ACTN3_mixed_actions,
        .nactions = 3,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "ADH1B",
        .status = "slow",
        .mechanism = "ADH1B affects the first step of alcohol metabolism (alcohol to acetaldehyde). Slow metabolizers have longer alcohol effects.",
        .implications = cc_ADH1B_slow_implications,
        .nimplications = 3,
        .actions = cc_ADH1B_slow_actions,
        .nactions = 3,
        .interactions = cc_ADH1B_slow_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "ADORA2A",
        .status = "anxiety_prone",
        .mechanism = "ADORA2A encodes adenosine receptors. This variant is associated with increased anxiety response to caffeine.",
        .implications = cc_ADORA2A_anxiety_prone_implications,
        .nimplications = 2,
        .actions = cc_ADORA2A_anxiety_prone_actions,
        .nactions = 4,
        .interactions = cc_ADORA2A_anxiety_prone_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "ADORA2A",
        .status = "lower_sensitivity",
        .mechanism = "This variant is associated with lower caffeine sensitivity regarding anxiety.",
        .implications = cc_ADORA2A_lower_sensitivity_implications,
        .nimplications = 2,
        .actions = cc_ADORA2A_lower_sensitivity_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "ADRB2",
        .status = "gly16",
        .mechanism = "ADRB2 Gly16 is associated with enhanced lipolysis (fat burning) response to exercise and catecholamines.",
        .implications = cc_ADRB2_gly16_implications,
        .nimplications = 2,
        .actions = cc_ADRB2_gly16_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "AGT",
        .status = "increased",
        .mechanism = "AGT M235T is associated with higher angiotensinogen levels, feeding into the renin-angiotensin system.",
        .implications = cc_AGT_increased_implications,
        .nimplications = 2,
        .actions = cc_AGT_increased_actions,
        .nactions = 2,
        .interactions = cc_AGT_increased_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "AGTR1",
        .status = "increased",
        .mechanism = "AGTR1 encodes the angiotensin II type 1 receptor. This variant is associated with increased receptor activity and hypertension risk.",
        .implications = cc_AGTR1_increased_implications,
        .nimplications = 2,
        .actions = cc_AGTR1_increased_actions,
        .nactions = 3,
        .interactions = cc_AGTR1_increased_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "APOA2",
        .status = "sensitive",
        .mechanism = "APOA2 affects how saturated fat influences body weight. The CC genotype shows strong correlation between saturated fat intake and obesity.",
        .implications = cc_APOA2_sensitive_implications,
        .nimplications = 2,
        .actions = cc_APOA2_sensitive_actions,
        .nactions = 4,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "ARNTL",
        .status = "significantly_altered",
        .mechanism = "BMAL1 (ARNTL) is a core circadian clock gene. This variant may weaken circadian rhythm strength.",
        .implications = cc_ARNTL_significantly_altered_implications,
        .nimplications = 3,
        .actions = cc_ARNTL_significantly_altered_actions,
        .nactions = 5,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "BCMO1",
        .status = "reduced",
        .mechanism = "BCMO1 converts beta-carotene to vitamin A. Reduced activity means less efficient conversion from plant sources.",
        .implications = cc_BCMO1_reduced_implications,
        .nimplications = 2,
        .actions = cc_BCMO1_reduced_actions,
        .nactions = 3,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "CETP",
        .status = "favorable",
        .mechanism = "CETP I405V affects cholesterol transfer between lipoproteins. This variant is associated with higher HDL and longevity.",
        .implications = cc_CETP_favorable_implications,
        .nimplications = 2,
        .actions = cc_CETP_favorable_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "COMT",
        .status = "slow",
        .mechanism = "COMT breaks down catecholamines (dopamine, norepinephrine, epinephrine). Slow COMT means these neurotransmitters remain active longer, leading to higher baseline levels.",
        .implications = cc_COMT_slow_implications,
        .nimplications = 5,
        .actions = cc_COMT_slow_actions,
        .nactions = 6,
        .interactions = cc_COMT_slow_interactions,
        .ninteractions = 2,
    },
    {
        .gene = "CYP1A2",
        .status = "intermediate",
        .mechanism = "CYP1A2 is the primary enzyme metabolizing caffeine. Intermediate metabolizers clear caffeine at a moderate rate, with ~5-6 hour half-life.",
        .implications = cc_CYP1A2_intermediate_implications,
        .nimplications = 3,
        .actions = cc_CYP1A2_intermediate_actions,
        .nactions = 3,
        .interactions = cc_CYP1A2_intermediate_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "CYP2C19",
        .status = "rapid",
        .mechanism = "CYP2C19*17 causes ultra-rapid metabolism of many drugs including PPIs, some antidepressants, and clopidogrel.",
        .implications = cc_CYP2C19_rapid_implications,
        .nimplications = 3,
        .actions = cc_CYP2C19_rapid_actions,
        .nactions = 3,
        .interactions = cc_CYP2C19_rapid_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "CYP3A5",
        .status = "non_expressor",
        .mechanism = "CYP3A5*3/*3 means you don't express CYP3A5. CYP3A4 handles the work. This is the most common genotype in many populations.",
        .implications = cc_CYP3A5_non_expressor_implications,
        .nimplications = 2,
        .actions = cc_CYP3A5_non_expressor_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "GC",
        .status = "low",
        .mechanism = "GC encodes vitamin D binding protein. This variant results in lower circulating 25-OH vitamin D levels.",
        .implications = cc_GC_low_implications,
        .nimplications = 3,
        .actions = cc_GC_low_actions,
        .nactions = 5,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "GNB3",
        .status = "increased",
        .mechanism = "GNB3 C825T affects G-protein signaling, associated with hypertension and obesity risk.",
        .implications = cc_GNB3_increased_implications,
        .nimplications = 3,
        .actions = cc_GNB3_increased_actions,
        .nactions = 3,
        .interactions = cc_GNB3_increased_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "HFE",
        .status = "carrier",
        .mechanism = "HFE H63D is a minor hemochromatosis variant. Carriers have slightly increased iron absorption.",
        .implications = cc_HFE_carrier_implications,
        .nimplications = 3,
        .actions = cc_HFE_carrier_actions,
        .nactions = 3,
        .interactions = cc_HFE_carrier_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "HLA-DQA1",
        .status = "increased_risk",
        .mechanism = "HLA-DQ2.5 is strongly associated with celiac disease susceptibility. Not deterministic but increases risk.",
        .implications = cc_HLA_DQA1_increased_risk_implications,
        .nimplications = 3,
        .actions = cc_HLA_DQA1_increased_risk_actions,
        .nactions = 4,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "IL6",
        .status = "high",
        .mechanism = "IL-6 -174 G/G is associated with higher baseline IL-6 production, an inflammatory cytokine.",
        .implications = cc_IL6_high_implications,
        .nimplications = 3,
        .actions = cc_IL6_high_actions,
        .nactions = 5,
        .interactions = cc_IL6_high_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "MC1R",
        .status = "accelerated",
        .mechanism = "MC1R variants affect melanin production and skin aging. V92M is associated with accelerated skin aging.",
        .implications = cc_MC1R_accelerated_implications,
        .nimplications = 2,
        .actions = cc_MC1R_accelerated_actions,
        .nactions = 4,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "MTHFR",
        .status = "significantly_reduced",
        .mechanism = "The MTHFR enzyme converts folic acid to methylfolate (5-MTHF), the active form used by the body. With 70% reduced activity, you produce significantly less methylfolate, affecting over 200 methylation-dependent reactions.",
        .implications = cc_MTHFR_significantly_reduced_implications,
        .nimplications = 4,
        .actions = cc_MTHFR_significantly_reduced_actions,
        .nactions = 5,
        .interactions = cc_MTHFR_significantly_reduced_interactions,
        .ninteractions = 2,
    },
    {
        .gene = "MTRR",
        .status = "significantly_reduced",
        .mechanism = "MTRR regenerates methylcobalamin (methyl-B12), the active form of B12. Impaired MTRR means B12 recycling is less efficient, potentially leading to functional B12 deficiency even with normal blood levels.",
        .implications = cc_MTRR_significantly_reduced_implications,
        .nimplications = 3,
        .actions = cc_MTRR_significantly_reduced_actions,
        .nactions = 4,
        .interactions = cc_MTRR_significantly_reduced_interactions,
        .ninteractions = 2,
    },
    {
        .gene = "NAT2",
        .status = "intermediate",
        .mechanism = "NAT2 acetylates various drugs and toxins. Intermediate acetylators have moderate metabolism of NAT2 substrates.",
        .implications = cc_NAT2_intermediate_implications,
        .nimplications = 2,
        .actions = cc_NAT2_intermediate_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "OPRM1",
        .status = "altered",
        .mechanism = "OPRM1 encodes the mu-opioid receptor. The A118G variant alters receptor binding, affecting response to endorphins, opioid medications, and reward from alcohol.",
        .implications = cc_OPRM1_altered_implications,
        .nimplications = 3,
        .actions = cc_OPRM1_altered_actions,
        .nactions = 3,
        .interactions = cc_OPRM1_altered_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "PEMT",
        .status = "reduced",
        .mechanism = "PEMT creates phosphatidylcholine from phosphatidylethanolamine using SAMe. Reduced function means you rely more on dietary choline intake.",
        .implications = cc_PEMT_reduced_implications,
        .nimplications = 3,
        .actions = cc_PEMT_reduced_actions,
        .nactions = 3,
        .interactions = cc_PEMT_reduced_interactions,
        .ninteractions = 1,
    },
    {
        .gene = "SOD2",
        .status = "high_activity",
        .mechanism = "SOD2 (MnSOD) is a key mitochondrial antioxidant enzyme. High activity (Ala/Ala) provides efficient superoxide neutralization.",
        .implications = cc_SOD2_high_activity_implications,
        .nimplications = 2,
        .actions = cc_SOD2_high_activity_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
    {
        .gene = "TP53",
        .status = "arg72",
        .mechanism = "TP53 R72P affects p53 apoptotic efficiency. Arg72 has less efficient apoptosis induction.",
        .implications = cc_TP53_arg72_implications,
        .nimplications = 2,
        .actions = cc_TP53_arg72_actions,
        .nactions = 2,
        .interactions = NULL,
        .ninteractions = 0,
    },
};
const size_t GH_CLINICAL_CONTEXT_COUNT = sizeof(GH_CLINICAL_CONTEXT) / sizeof(GH_CLINICAL_CONTEXT[0]);

