/* Generated by c/tools/gen_dosing_data.py -- do not edit.
 * Sources: drug_dosing.py, polypharmacy.py, preventive_care.py
 */

#include "gh_dosing.h"

#include <stddef.h>

static const char *const dose_warfarin_genes[] = {
    "CYP2C9",
    "VKORC1",
};
static const char *const dose_warfarin_r0_values[] = {
    "intermediate",
    "poor",
};
static const char *const dose_warfarin_r1_values[] = {
    "high_sensitivity",
    "sensitive",
};
static const gh_dose_rule dose_warfarin_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP2C9",
        .values = dose_warfarin_r0_values,
        .nvalues = 2,
        .action = "Reduce warfarin starting dose by 25-50%. CYP2C9 intermediate/poor metabolizers clear warfarin more slowly, increasing bleeding risk.",
        .dose_guidance = "Consider starting at 2-3 mg/day instead of standard 5 mg/day.",
    },
    {
        .source = GH_DOSE_FINDING,
        .gene = "VKORC1",
        .values = dose_warfarin_r1_values,
        .nvalues = 2,
        .action = "VKORC1 sensitivity detected \342\200\224 warfarin target dose likely 1-3 mg/day. Requires careful INR monitoring.",
        .dose_guidance = "Start low (1-2 mg/day), titrate to INR 2.0-3.0.",
    },
};

static const char *const dose_clopidogrel_genes[] = {
    "CYP2C19",
};
static const char *const dose_clopidogrel_r0_values[] = {
    "intermediate",
    "poor",
};
static const char *const dose_clopidogrel_r1_values[] = {
    "ultrarapid",
};
static const gh_dose_rule dose_clopidogrel_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP2C19",
        .values = dose_clopidogrel_r0_values,
        .nvalues = 2,
        .action = "Reduced CYP2C19 function \342\200\224 clopidogrel may not be adequately activated. Consider prasugrel or ticagrelor as alternatives.",
        .dose_guidance = "Avoid clopidogrel if possible. Use prasugrel 10mg or ticagrelor 90mg twice daily.",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP2C19",
        .values = dose_clopidogrel_r1_values,
        .nvalues = 1,
        .action = "Ultrarapid CYP2C19 \342\200\224 standard clopidogrel dosing is appropriate. Enhanced activation may increase bleeding risk at higher doses.",
        .dose_guidance = "Standard 75 mg/day is appropriate.",
    },
};

static const char *const dose_codeine_genes[] = {
    "CYP2D6",
};
static const char *const dose_codeine_r0_values[] = {
    "poor",
};
static const char *const dose_codeine_r1_values[] = {
    "ultrarapid",
};
static const char *const dose_codeine_r2_values[] = {
    "intermediate",
};
static const gh_dose_rule dose_codeine_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP2D6",
        .values = dose_codeine_r0_values,
        .nvalues = 1,
        .action = "CYP2D6 poor metabolizer \342\200\224 codeine will NOT be converted to morphine. No analgesic effect expected. Use alternative pain medication.",
        .dose_guidance = "Avoid codeine entirely. Use non-opioid analgesics or morphine/oxycodone at standard doses.",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP2D6",
        .values = dose_codeine_r1_values,
        .nvalues = 1,
        .action = "CYP2D6 ultrarapid metabolizer \342\200\224 codeine is converted to morphine too rapidly, risking respiratory depression. AVOID codeine.",
        .dose_guidance = "CONTRAINDICATED. Use non-opioid alternatives or morphine at reduced doses with monitoring.",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP2D6",
        .values = dose_codeine_r2_values,
        .nvalues = 1,
        .action = "CYP2D6 intermediate metabolizer \342\200\224 reduced codeine activation. May have suboptimal pain relief.",
        .dose_guidance = "Consider alternative analgesics if inadequate pain relief at standard doses.",
    },
};

static const char *const dose_simvastatin_genes[] = {
    "SLCO1B1",
};
static const char *const dose_simvastatin_r0_values[] = {
    "intermediate",
    "poor",
};
static const gh_dose_rule dose_simvastatin_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "SLCO1B1",
        .values = dose_simvastatin_r0_values,
        .nvalues = 2,
        .action = "SLCO1B1 decreased function \342\200\224 elevated simvastatin myopathy risk (5-17x). Avoid simvastatin >20mg or switch statin.",
        .dose_guidance = "Use simvastatin \342\211\24420 mg/day, or switch to rosuvastatin/pravastatin which are less affected.",
    },
};

static const char *const dose_fluoropyrimidines_genes[] = {
    "DPYD",
};
static const char *const dose_fluoropyrimidines_r0_values[] = {
    "poor",
};
static const char *const dose_fluoropyrimidines_r1_values[] = {
    "intermediate",
};
static const gh_dose_rule dose_fluoropyrimidines_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "DPYD",
        .values = dose_fluoropyrimidines_r0_values,
        .nvalues = 1,
        .action = "DPYD deficient \342\200\224 fluoropyrimidine chemotherapy (5-FU, capecitabine) can be FATAL. Complete dose avoidance or alternative regimen required.",
        .dose_guidance = "CONTRAINDICATED at full dose. If no alternative, start at \342\211\24425% dose with intensive monitoring.",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "DPYD",
        .values = dose_fluoropyrimidines_r1_values,
        .nvalues = 1,
        .action = "DPYD intermediate metabolizer \342\200\224 start fluoropyrimidines at 50% reduced dose with dose escalation based on tolerance.",
        .dose_guidance = "Start at 50% dose. Escalate in subsequent cycles if tolerated.",
    },
};

static const char *const dose_thiopurines_genes[] = {
    "TPMT",
};
static const char *const dose_thiopurines_r0_values[] = {
    "poor",
};
static const char *const dose_thiopurines_r1_values[] = {
    "intermediate",
};
static const gh_dose_rule dose_thiopurines_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "TPMT",
        .values = dose_thiopurines_r0_values,
        .nvalues = 1,
        .action = "TPMT deficient \342\200\224 standard thiopurine doses (azathioprine, 6-MP) cause life-threatening myelosuppression. Drastic dose reduction required.",
        .dose_guidance = "Reduce dose to 10% of standard. Start azathioprine at 0.5 mg/kg/day (vs standard 2-3 mg/kg/day).",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "TPMT",
        .values = dose_thiopurines_r1_values,
        .nvalues = 1,
        .action = "TPMT intermediate metabolizer \342\200\224 reduce thiopurine starting dose by 30-50%.",
        .dose_guidance = "Start at 50% dose (azathioprine ~1-1.5 mg/kg/day). Monitor CBC weekly for first month.",
    },
};

static const char *const dose_tacrolimus_genes[] = {
    "CYP3A5",
};
static const char *const dose_tacrolimus_r0_values[] = {
    "normal",
};
static const char *const dose_tacrolimus_r1_values[] = {
    "intermediate",
    "poor",
};
static const gh_dose_rule dose_tacrolimus_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP3A5",
        .values = dose_tacrolimus_r0_values,
        .nvalues = 1,
        .action = "CYP3A5 expresser \342\200\224 requires higher tacrolimus doses to reach therapeutic levels. Standard dosing may be subtherapeutic.",
        .dose_guidance = "Start at 0.3 mg/kg/day (1.5-2x standard). Monitor trough levels closely.",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP3A5",
        .values = dose_tacrolimus_r1_values,
        .nvalues = 2,
        .action = "CYP3A5 non-expresser \342\200\224 standard tacrolimus dosing appropriate.",
        .dose_guidance = "Start at 0.15 mg/kg/day (standard). Monitor trough levels per protocol.",
    },
};

static const char *const dose_isoniazid_genes[] = {
    "NAT2",
};
static const char *const dose_isoniazid_r0_values[] = {
    "intermediate",
    "poor",
};
static const gh_dose_rule dose_isoniazid_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "NAT2",
        .values = dose_isoniazid_r0_values,
        .nvalues = 2,
        .action = "NAT2 slow acetylator \342\200\224 increased risk of isoniazid-induced hepatotoxicity and peripheral neuropathy. Supplement with pyridoxine.",
        .dose_guidance = "Standard dose but ADD pyridoxine (vitamin B6) 25-50 mg/day to prevent neuropathy. Monitor liver function.",
    },
};

static const char *const dose_caffeine_genes[] = {
    "CYP1A2",
};
static const char *const dose_caffeine_r0_values[] = {
    "intermediate",
    "poor",
};
static const char *const dose_caffeine_r1_values[] = {
    "normal",
    "rapid",
    "ultrarapid",
};
static const gh_dose_rule dose_caffeine_rules[] = {
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP1A2",
        .values = dose_caffeine_r0_values,
        .nvalues = 2,
        .action = "CYP1A2 slow metabolizer \342\200\224 caffeine stays active longer. Limit to 1-2 cups before noon to protect sleep and cardiovascular health.",
        .dose_guidance = "\342\211\244200 mg caffeine/day (~2 cups coffee), none after 12 PM.",
    },
    {
        .source = GH_DOSE_STAR,
        .gene = "CYP1A2",
        .values = dose_caffeine_r1_values,
        .nvalues = 3,
        .action = "CYP1A2 normal/rapid metabolizer \342\200\224 standard caffeine clearance. Moderate intake (3-4 cups/day) generally well tolerated.",
        .dose_guidance = "Up to 400 mg caffeine/day (~4 cups) is generally safe.",
    },
};

const gh_dose_drug GH_DOSE_DRUGS[] = {
    {
        .drug = "warfarin",
        .display = "Warfarin",
        .category = "anticoagulant",
        .genes = dose_warfarin_genes,
        .ngenes = 2,
        .rules = dose_warfarin_rules,
        .nrules = 2,
        .source = "CPIC Guideline for Warfarin (Johnson et al. 2017, PMID: 28198005)",
    },
    {
        .drug = "clopidogrel",
        .display = "Clopidogrel",
        .category = "antiplatelet",
        .genes = dose_clopidogrel_genes,
        .ngenes = 1,
        .rules = dose_clopidogrel_rules,
        .nrules = 2,
        .source = "CPIC Guideline for Clopidogrel (Scott et al. 2013, PMID: 23698643)",
    },
    {
        .drug = "codeine",
        .display = "Codeine",
        .category = "analgesic",
        .genes = dose_codeine_genes,
        .ngenes = 1,
        .rules = dose_codeine_rules,
        .nrules = 3,
        .source = "CPIC Guideline for Codeine (Crews et al. 2014, PMID: 24458010)",
    },
    {
        .drug = "simvastatin",
        .display = "Simvastatin",
        .category = "statin",
        .genes = dose_simvastatin_genes,
        .ngenes = 1,
        .rules = dose_simvastatin_rules,
        .nrules = 1,
        .source = "CPIC Guideline for Simvastatin (Ramsey et al. 2014, PMID: 24918167)",
    },
    {
        .drug = "fluoropyrimidines",
        .display = "Fluoropyrimidines",
        .category = "chemotherapy",
        .genes = dose_fluoropyrimidines_genes,
        .ngenes = 1,
        .rules = dose_fluoropyrimidines_rules,
        .nrules = 2,
        .source = "CPIC Guideline for Fluoropyrimidines (Amstutz et al. 2018, PMID: 29152729)",
    },
    {
        .drug = "thiopurines",
        .display = "Thiopurines",
        .category = "immunosuppressant",
        .genes = dose_thiopurines_genes,
        .ngenes = 1,
        .rules = dose_thiopurines_rules,
        .nrules = 2,
        .source = "CPIC Guideline for Thiopurines (Relling et al. 2019, PMID: 30447069)",
    },
    {
        .drug = "tacrolimus",
        .display = "Tacrolimus",
        .category = "immunosuppressant",
        .genes = dose_tacrolimus_genes,
        .ngenes = 1,
        .rules = dose_tacrolimus_rules,
        .nrules = 2,
        .source = "CPIC Guideline for Tacrolimus (Birdwell et al. 2015, PMID: 25801146)",
    },
    {
        .drug = "isoniazid",
        .display = "Isoniazid",
        .category = "antibiotic",
        .genes = dose_isoniazid_genes,
        .ngenes = 1,
        .rules = dose_isoniazid_rules,
        .nrules = 1,
        .source = "DPWG Guideline for Isoniazid (Swen et al. 2011, PMID: 21412232)",
    },
    {
        .drug = "caffeine",
        .display = "Caffeine",
        .category = "dietary",
        .genes = dose_caffeine_genes,
        .ngenes = 1,
        .rules = dose_caffeine_rules,
        .nrules = 2,
        .source = "Cornelis et al. 2006, JAMA (PMID: 16522833)",
    },
};
const size_t GH_DOSE_DRUG_COUNT = sizeof(GH_DOSE_DRUGS) / sizeof(GH_DOSE_DRUGS[0]);

static const char *const poly_warfarin_compound_CYP2C9[] = {
    "poor",
    "intermediate",
};
static const char *const poly_warfarin_compound_VKORC1[] = {
    "sensitive",
    "highly_sensitive",
};
static const gh_poly_gene poly_warfarin_compound_genes[] = {
    {"CYP2C9", poly_warfarin_compound_CYP2C9, 2},
    {"VKORC1", poly_warfarin_compound_VKORC1, 2},
};
static const char *const poly_warfarin_compound_drugs[] = {
    "warfarin",
    "acenocoumarol",
};

static const char *const poly_opioid_sensitivity_CYP2D6[] = {
    "poor",
    "intermediate",
};
static const char *const poly_opioid_sensitivity_OPRM1[] = {
    "reduced",
    "altered",
};
static const gh_poly_gene poly_opioid_sensitivity_genes[] = {
    {"CYP2D6", poly_opioid_sensitivity_CYP2D6, 2},
    {"OPRM1", poly_opioid_sensitivity_OPRM1, 2},
};
static const char *const poly_opioid_sensitivity_drugs[] = {
    "codeine",
    "tramadol",
    "oxycodone",
    "hydrocodone",
};

static const char *const poly_ssri_sensitivity_CYP2C19[] = {
    "poor",
    "intermediate",
};
static const char *const poly_ssri_sensitivity_COMT[] = {
    "slow",
};
static const gh_poly_gene poly_ssri_sensitivity_genes[] = {
    {"CYP2C19", poly_ssri_sensitivity_CYP2C19, 2},
    {"COMT", poly_ssri_sensitivity_COMT, 1},
};
static const char *const poly_ssri_sensitivity_drugs[] = {
    "citalopram",
    "escitalopram",
    "sertraline",
    "amitriptyline",
};

static const char *const poly_statin_myopathy_SLCO1B1[] = {
    "reduced",
    "poor_transporter",
};
static const gh_poly_gene poly_statin_myopathy_genes[] = {
    {"SLCO1B1", poly_statin_myopathy_SLCO1B1, 2},
};
static const char *const poly_statin_myopathy_drugs[] = {
    "simvastatin",
    "atorvastatin",
    "rosuvastatin",
};

static const char *const poly_chemo_toxicity_DPYD[] = {
    "poor",
    "intermediate",
};
static const gh_poly_gene poly_chemo_toxicity_genes[] = {
    {"DPYD", poly_chemo_toxicity_DPYD, 2},
};
static const char *const poly_chemo_toxicity_drugs[] = {
    "5-fluorouracil",
    "capecitabine",
    "tegafur",
};

static const char *const poly_thiopurine_toxicity_TPMT[] = {
    "poor",
    "intermediate",
};
static const gh_poly_gene poly_thiopurine_toxicity_genes[] = {
    {"TPMT", poly_thiopurine_toxicity_TPMT, 2},
};
static const char *const poly_thiopurine_toxicity_drugs[] = {
    "azathioprine",
    "6-mercaptopurine",
    "thioguanine",
};

static const char *const poly_cyp2d6_ultrarapid_codeine_CYP2D6[] = {
    "ultrarapid",
    "rapid",
};
static const gh_poly_gene poly_cyp2d6_ultrarapid_codeine_genes[] = {
    {"CYP2D6", poly_cyp2d6_ultrarapid_codeine_CYP2D6, 2},
};
static const char *const poly_cyp2d6_ultrarapid_codeine_drugs[] = {
    "codeine",
    "tramadol",
};

static const char *const poly_ppi_reduced_efficacy_CYP2C19[] = {
    "ultrarapid",
    "rapid",
};
static const gh_poly_gene poly_ppi_reduced_efficacy_genes[] = {
    {"CYP2C19", poly_ppi_reduced_efficacy_CYP2C19, 2},
};
static const char *const poly_ppi_reduced_efficacy_drugs[] = {
    "omeprazole",
    "lansoprazole",
    "pantoprazole",
};

static const char *const poly_clopidogrel_resistance_CYP2C19[] = {
    "poor",
    "intermediate",
};
static const gh_poly_gene poly_clopidogrel_resistance_genes[] = {
    {"CYP2C19", poly_clopidogrel_resistance_CYP2C19, 2},
};
static const char *const poly_clopidogrel_resistance_drugs[] = {
    "clopidogrel",
};

const gh_poly_rule GH_POLY_RULES[] = {
    {
        .id = "warfarin_compound",
        .name = "Warfarin Compound Sensitivity",
        .severity = "high",
        .genes = poly_warfarin_compound_genes,
        .ngenes = 2,
        .drugs_affected = poly_warfarin_compound_drugs,
        .ndrugs = 2,
        .warning = "CYP2C9 reduced metabolism + VKORC1 increased sensitivity = compounded warfarin sensitivity. Standard doses may cause dangerous bleeding. Require 50-80% dose reduction.",
        .action = "Use FDA-approved warfarin dosing algorithm incorporating both CYP2C9 and VKORC1 genotypes. Consider direct oral anticoagulants (DOACs) as alternatives. INR monitoring critical.",
    },
    {
        .id = "opioid_sensitivity",
        .name = "Opioid Response Complexity",
        .severity = "high",
        .genes = poly_opioid_sensitivity_genes,
        .ngenes = 2,
        .drugs_affected = poly_opioid_sensitivity_drugs,
        .ndrugs = 4,
        .warning = "Poor CYP2D6 metabolism prevents conversion of codeine/tramadol to active metabolites. Combined with altered opioid receptor sensitivity, pain relief may be minimal or unpredictable.",
        .action = "Avoid codeine and tramadol (prodrugs requiring CYP2D6). Use morphine or non-opioid alternatives. If opioids necessary, titrate carefully with pain specialist guidance.",
    },
    {
        .id = "ssri_sensitivity",
        .name = "SSRI/Antidepressant Sensitivity Triad",
        .severity = "moderate",
        .genes = poly_ssri_sensitivity_genes,
        .ngenes = 2,
        .drugs_affected = poly_ssri_sensitivity_drugs,
        .ndrugs = 4,
        .warning = "Slow CYP2C19 metabolism increases SSRI blood levels. Combined with slow COMT (elevated catecholamines), serotonin syndrome risk is elevated. Activation side effects more likely.",
        .action = "Start SSRIs at 50% standard dose. Monitor for activation, agitation, or serotonergic symptoms. CYP2C19-metabolized SSRIs (citalopram, escitalopram) especially affected. Consider alternatives like bupropion or mirtazapine.",
    },
    {
        .id = "statin_myopathy",
        .name = "Statin Myopathy Risk",
        .severity = "moderate",
        .genes = poly_statin_myopathy_genes,
        .ngenes = 1,
        .drugs_affected = poly_statin_myopathy_drugs,
        .ndrugs = 3,
        .warning = "Reduced SLCO1B1 transport increases statin blood levels, raising myopathy risk 5-17x with simvastatin. Higher risk when combined with CYP3A4 inhibitors (clarithromycin, itraconazole, grapefruit).",
        .action = "Avoid simvastatin >20mg. Prefer pravastatin or rosuvastatin (lower myopathy risk). Avoid concurrent CYP3A4 inhibitors. Monitor CK levels if muscle symptoms appear.",
    },
    {
        .id = "chemo_toxicity",
        .name = "Chemotherapy Toxicity Risk",
        .severity = "high",
        .genes = poly_chemo_toxicity_genes,
        .ngenes = 1,
        .drugs_affected = poly_chemo_toxicity_drugs,
        .ndrugs = 3,
        .warning = "DPYD deficiency can cause fatal fluoropyrimidine toxicity. Even partial deficiency (intermediate metabolizer) requires 50% dose reduction. This is a life-threatening interaction.",
        .action = "MANDATORY pre-treatment DPYD testing before any fluoropyrimidine. Intermediate metabolizers: reduce dose by 50%. Poor metabolizers: contraindicated. Consider alternative chemotherapy regimens.",
    },
    {
        .id = "thiopurine_toxicity",
        .name = "Thiopurine Myelosuppression Risk",
        .severity = "high",
        .genes = poly_thiopurine_toxicity_genes,
        .ngenes = 1,
        .drugs_affected = poly_thiopurine_toxicity_drugs,
        .ndrugs = 3,
        .warning = "TPMT deficiency causes accumulation of cytotoxic thioguanine nucleotides, leading to life-threatening myelosuppression. Even intermediate metabolizers need dose adjustments.",
        .action = "Intermediate metabolizers: reduce thiopurine dose by 30-50%. Poor metabolizers: reduce by 90% or use alternative. Monitor CBC weekly for first 8 weeks of therapy.",
    },
    {
        .id = "cyp2d6_ultrarapid_codeine",
        .name = "Ultrarapid CYP2D6 + Codeine Toxicity",
        .severity = "high",
        .genes = poly_cyp2d6_ultrarapid_codeine_genes,
        .ngenes = 1,
        .drugs_affected = poly_cyp2d6_ultrarapid_codeine_drugs,
        .ndrugs = 2,
        .warning = "Ultrarapid CYP2D6 metabolism converts codeine to morphine too quickly, causing respiratory depression. Fatal cases reported, especially in children and breastfeeding mothers.",
        .action = "AVOID codeine completely. Use non-CYP2D6 alternatives: morphine (already active), NSAIDs, or acetaminophen. If breastfeeding, codeine is contraindicated.",
    },
    {
        .id = "ppi_reduced_efficacy",
        .name = "PPI Reduced Efficacy (Ultrarapid CYP2C19)",
        .severity = "moderate",
        .genes = poly_ppi_reduced_efficacy_genes,
        .ngenes = 1,
        .drugs_affected = poly_ppi_reduced_efficacy_drugs,
        .ndrugs = 3,
        .warning = "Ultrarapid CYP2C19 clears PPIs too fast, reducing acid suppression. H. pylori eradication rates drop significantly. Standard PPI doses may be insufficient.",
        .action = "Increase PPI dose or switch to rabeprazole (less CYP2C19 dependent). For H. pylori: use higher-dose PPI regimens. Consider vonoprazan if available.",
    },
    {
        .id = "clopidogrel_resistance",
        .name = "Clopidogrel Resistance (Poor CYP2C19)",
        .severity = "high",
        .genes = poly_clopidogrel_resistance_genes,
        .ngenes = 1,
        .drugs_affected = poly_clopidogrel_resistance_drugs,
        .ndrugs = 1,
        .warning = "CYP2C19 is required to activate clopidogrel. Poor/intermediate metabolizers have reduced antiplatelet effect, increasing risk of stent thrombosis and cardiovascular events.",
        .action = "Use alternative antiplatelet: prasugrel or ticagrelor (not CYP2C19 dependent). FDA black box warning on clopidogrel for poor CYP2C19 metabolizers.",
    },
};
const size_t GH_POLY_RULE_COUNT = sizeof(GH_POLY_RULES) / sizeof(GH_POLY_RULES[0]);

const gh_base_screening GH_BASE_SCREENINGS[] = {
    {"Blood pressure", 18, "Every 1-2 years", "hypertension", "USPSTF"},
    {"Lipid panel", 35, "Every 5 years", "cardiovascular", "USPSTF"},
    {"Fasting glucose / HbA1c", 35, "Every 3 years", "type2_diabetes", "USPSTF/ADA"},
    {"Colorectal cancer screening", 45, "Every 10 years (colonoscopy)", "colorectal_cancer", "USPSTF"},
    {"Mammography", 50, "Every 2 years", "breast_cancer", "USPSTF"},
    {"PSA test (discuss with doctor)", 55, "Shared decision", "prostate_cancer", "USPSTF"},
    {"Eye exam (dilated)", 60, "Every 1-2 years", "age_related_macular_degeneration", "AAO"},
    {"DEXA bone density scan", 65, "Every 2 years", "osteoporosis", "USPSTF"},
};
const size_t GH_BASE_SCREENING_COUNT = sizeof(GH_BASE_SCREENINGS) / sizeof(GH_BASE_SCREENINGS[0]);

const gh_screening_modifier GH_PRS_ELEVATED_MODIFIERS[] = {
    {"hypertension", -10, "Annually", "Elevated genetic risk for hypertension"},
    {"type2_diabetes", -10, "Annually", "Elevated genetic risk for type 2 diabetes"},
    {"coronary_artery_disease", -10, "Every 2 years", "Elevated genetic risk for coronary artery disease"},
    {"breast_cancer", -10, "Annually", "Elevated genetic risk for breast cancer"},
    {"colorectal_cancer", -5, "Every 5 years", "Elevated genetic risk for colorectal cancer"},
    {"prostate_cancer", -10, "Every 2 years", "Elevated genetic risk for prostate cancer"},
    {"age_related_macular_degeneration", -10, "Annually", "Elevated genetic risk for AMD"},
    {"osteoporosis", -10, "Every 2 years", "Elevated genetic risk for osteoporosis"},
    {"parkinsons_disease", 0, "Discuss with neurologist", "Elevated genetic risk for Parkinson's disease"},
    {"celiac_disease", 0, "If symptomatic", "Elevated genetic risk for celiac disease \342\200\224 test tTG-IgA if GI symptoms"},
    {"rheumatoid_arthritis", 0, "If symptomatic", "Elevated genetic risk for RA \342\200\224 test anti-CCP if joint symptoms"},
};
const size_t GH_PRS_ELEVATED_MODIFIERS_COUNT = sizeof(GH_PRS_ELEVATED_MODIFIERS) / sizeof(GH_PRS_ELEVATED_MODIFIERS[0]);

const gh_screening_modifier GH_PRS_HIGH_MODIFIERS[] = {
    {"hypertension", -15, "Every 6 months", "High genetic risk for hypertension"},
    {"type2_diabetes", -15, "Every 6 months", "High genetic risk for type 2 diabetes"},
    {"coronary_artery_disease", -15, "Annually", "High genetic risk for CAD \342\200\224 consider calcium score at 40"},
    {"breast_cancer", -15, "Annually + MRI", "High genetic risk for breast cancer"},
    {"colorectal_cancer", -10, "Every 3 years", "High genetic risk for colorectal cancer"},
};
const size_t GH_PRS_HIGH_MODIFIERS_COUNT = sizeof(GH_PRS_HIGH_MODIFIERS) / sizeof(GH_PRS_HIGH_MODIFIERS[0]);

const gh_apoe_screening GH_APOE_ELEVATED_SCREENINGS[] = {
    {"Lipid panel", 25, "Every 2 years", "APOE e4 carrier \342\200\224 earlier lipid monitoring recommended"},
    {"Cognitive screening", 55, "Every 2 years", "APOE e4 \342\200\224 proactive cognitive health monitoring"},
};
const size_t GH_APOE_ELEVATED_SCREENINGS_COUNT = sizeof(GH_APOE_ELEVATED_SCREENINGS) / sizeof(GH_APOE_ELEVATED_SCREENINGS[0]);

const gh_apoe_screening GH_APOE_HIGH_SCREENINGS[] = {
    {"Lipid panel", 20, "Annually", "APOE e4/e4 \342\200\224 aggressive lipid management recommended"},
    {"Cognitive screening", 50, "Annually", "APOE e4/e4 \342\200\224 early cognitive screening advised"},
    {"Amyloid PET (discuss)", 55, "Discuss with neurologist", "APOE e4/e4 \342\200\224 consider amyloid imaging"},
};
const size_t GH_APOE_HIGH_SCREENINGS_COUNT = sizeof(GH_APOE_HIGH_SCREENINGS) / sizeof(GH_APOE_HIGH_SCREENINGS[0]);

