/* Generated by c/tools/gen_dependent_profiles.py -- do not edit.
 * Sources: sleep_profile.py, nutrigenomics.py, mental_health.py,
 *          longevity.py
 */

#include "gh_dependent_profiles.h"

#include <stddef.h>

const gh_chronotype_snp GH_CHRONOTYPE_SNPS[] = {
    {"rs1801260", "CLOCK", "chronotype", 'G', 1.0, "CLOCK 3111T>C \342\200\224 evening preference"},
    {"rs2304672", "PER2", "chronotype", 'C', 0.7, "CLOCK \342\200\224 additional chronotype variant"},
    {"rs934945", "PER2", "chronotype", 'C', 0.9, "PER2 \342\200\224 period circadian protein 2"},
    {"rs228697", "PER3", "chronotype", 'C', 0.8, "PER3 \342\200\224 short sleep tolerance, evening preference"},
    {"rs2278749", "ARNTL", "chronotype", 'T', 0.6, "BMAL1/ARNTL \342\200\224 core circadian oscillator"},
    {"rs2305160", "NPAS2", "chronotype", 'G', 0.7, "NPAS2 \342\200\224 neuronal PAS domain protein 2"},
    {"rs10830963", "MTNR1B", "melatonin", 'G', 0.8, "Melatonin receptor 1B \342\200\224 delayed melatonin onset"},
    {"rs6295", "HTR1A", "sleep_quality", 'G', 0.5, "Serotonin 1A receptor \342\200\224 REM sleep regulation"},
    {"rs73598374", "ADA", "sleep_depth", 'T', 0.7, "Adenosine deaminase \342\200\224 deep sleep pressure"},
};
const size_t GH_CHRONOTYPE_SNP_COUNT = sizeof(GH_CHRONOTYPE_SNPS) / sizeof(GH_CHRONOTYPE_SNPS[0]);

static const gh_status_weight nut_folate_methylfolate_MTHFR[] = {
    {"reduced", 0.5},
    {"severely_reduced", 1.0},
};
static const gh_status_weight nut_folate_methylfolate_MTRR[] = {
    {"reduced", 0.3},
    {"severely_reduced", 0.7},
};
static const gh_status_weight nut_folate_methylfolate_MTR[] = {
    {"reduced", 0.4},
};
static const gh_nutrient_gene nut_folate_methylfolate_genes[] = {
    {"MTHFR", "Reduced conversion of folic acid to active 5-MTHF", nut_folate_methylfolate_MTHFR, 2},
    {"MTRR", "Impaired B12 recycling reduces methionine synthase activity", nut_folate_methylfolate_MTRR, 2},
    {"MTR", "Reduced methionine synthase activity", nut_folate_methylfolate_MTR, 1},
};

static const gh_status_weight nut_vitamin_b12_MTRR[] = {
    {"reduced", 0.3},
    {"severely_reduced", 0.6},
};
static const gh_status_weight nut_vitamin_b12_FUT2[] = {
    {"non_secretor", 0.5},
};
static const gh_nutrient_gene nut_vitamin_b12_genes[] = {
    {"MTRR", "Impaired B12 recycling \342\200\224 may need higher intake", nut_vitamin_b12_MTRR, 2},
    {"FUT2", "Non-secretors have ~35% lower B12 absorption from food", nut_vitamin_b12_FUT2, 1},
};

static const gh_status_weight nut_vitamin_d_VDR[] = {
    {"reduced", 0.4},
    {"low_sensitivity", 0.5},
};
static const gh_status_weight nut_vitamin_d_GC[] = {
    {"reduced", 0.5},
    {"low_binding", 0.6},
};
static const gh_status_weight nut_vitamin_d_CYP2R1[] = {
    {"reduced", 0.5},
};
static const gh_nutrient_gene nut_vitamin_d_genes[] = {
    {"VDR", "Reduced vitamin D receptor sensitivity", nut_vitamin_d_VDR, 2},
    {"GC", "Lower vitamin D binding protein \342\200\224 reduced transport", nut_vitamin_d_GC, 2},
    {"CYP2R1", "Reduced 25-hydroxylation of vitamin D in liver", nut_vitamin_d_CYP2R1, 1},
};

static const gh_status_weight nut_iron_HFE[] = {
    {"carrier", -0.3},
    {"homozygous", -0.8},
};
static const gh_nutrient_gene nut_iron_genes[] = {
    {"HFE", "Increased iron absorption \342\200\224 risk of iron overload", nut_iron_HFE, 2},
};

static const gh_status_weight nut_choline_PEMT[] = {
    {"reduced", 0.6},
};
static const gh_status_weight nut_choline_MTHFR[] = {
    {"reduced", 0.3},
    {"severely_reduced", 0.5},
};
static const gh_nutrient_gene nut_choline_genes[] = {
    {"PEMT", "Reduced endogenous choline synthesis \342\200\224 higher dietary need", nut_choline_PEMT, 1},
    {"MTHFR", "Impaired methylation increases choline demand as alternate methyl donor", nut_choline_MTHFR, 2},
};

static const gh_status_weight nut_omega3_FADS1[] = {
    {"reduced", 0.5},
    {"low_conversion", 0.7},
};
static const gh_nutrient_gene nut_omega3_genes[] = {
    {"FADS1", "Reduced ALA\342\206\222EPA\342\206\222DHA conversion (FADS1/2 desaturase)", nut_omega3_FADS1, 2},
};

static const gh_status_weight nut_magnesium_COMT[] = {
    {"slow", 0.4},
};
static const gh_nutrient_gene nut_magnesium_genes[] = {
    {"COMT", "Slow COMT needs magnesium as cofactor; increased demand", nut_magnesium_COMT, 1},
};

static const gh_status_weight nut_vitamin_a_BCMO1[] = {
    {"reduced", 0.5},
    {"poor_converter", 0.8},
};
static const gh_nutrient_gene nut_vitamin_a_genes[] = {
    {"BCMO1", "Reduced beta-carotene to retinol conversion (up to 70% lower)", nut_vitamin_a_BCMO1, 2},
};

const gh_nutrient_profile GH_NUTRIENT_PROFILES[] = {
    {
        .id = "folate_methylfolate",
        .name = "Folate / Methylfolate (B9)",
        .supplement_form = "L-methylfolate (5-MTHF) \342\200\224 NOT folic acid",
        .dose_range = "400-800 mcg methylfolate/day",
        .testing = "Serum folate, homocysteine, RBC folate",
        .genes = nut_folate_methylfolate_genes,
        .ngenes = 3,
        .food_sources = "Leafy greens, legumes, liver, fortified grains",
    },
    {
        .id = "vitamin_b12",
        .name = "Vitamin B12 (Cobalamin)",
        .supplement_form = "Methylcobalamin or adenosylcobalamin (sublingual)",
        .dose_range = "1000-5000 mcg methylcobalamin/day if deficient",
        .testing = "Serum B12, methylmalonic acid (MMA), homocysteine",
        .genes = nut_vitamin_b12_genes,
        .ngenes = 2,
        .food_sources = "Meat, fish, eggs, dairy, fortified nutritional yeast",
    },
    {
        .id = "vitamin_d",
        .name = "Vitamin D",
        .supplement_form = "Vitamin D3 (cholecalciferol) with K2 (MK-7)",
        .dose_range = "2000-5000 IU D3/day (adjust by serum levels)",
        .testing = "Serum 25-OH vitamin D (target 40-60 ng/mL)",
        .genes = nut_vitamin_d_genes,
        .ngenes = 3,
        .food_sources = "Fatty fish, egg yolks, fortified foods, sunlight exposure",
    },
    {
        .id = "iron",
        .name = "Iron",
        .supplement_form = "Iron bisglycinate (if deficient) \342\200\224 AVOID if HFE homozygous",
        .dose_range = "18-30 mg elemental iron/day (only if deficient)",
        .testing = "Ferritin, serum iron, TIBC, transferrin saturation",
        .genes = nut_iron_genes,
        .ngenes = 1,
        .food_sources = "Red meat, organ meats, shellfish, legumes, dark leafy greens",
    },
    {
        .id = "choline",
        .name = "Choline",
        .supplement_form = "CDP-choline (citicoline) or phosphatidylcholine",
        .dose_range = "250-500 mg citicoline/day",
        .testing = "No standard clinical test; assess dietary intake",
        .genes = nut_choline_genes,
        .ngenes = 2,
        .food_sources = "Eggs (yolks), liver, beef, fish, cruciferous vegetables",
    },
    {
        .id = "omega3",
        .name = "Omega-3 (EPA/DHA)",
        .supplement_form = "Fish oil (EPA+DHA) or algal DHA",
        .dose_range = "1000-2000 mg combined EPA+DHA/day",
        .testing = "Omega-3 index blood test (target >8%)",
        .genes = nut_omega3_genes,
        .ngenes = 1,
        .food_sources = "Fatty fish (salmon, sardines, mackerel), algae",
    },
    {
        .id = "magnesium",
        .name = "Magnesium",
        .supplement_form = "Magnesium glycinate or threonate (best bioavailability)",
        .dose_range = "300-400 mg elemental magnesium/day",
        .testing = "RBC magnesium (not serum \342\200\224 serum is unreliable)",
        .genes = nut_magnesium_genes,
        .ngenes = 1,
        .food_sources = "Dark chocolate, nuts, seeds, leafy greens, avocado",
    },
    {
        .id = "vitamin_a",
        .name = "Vitamin A (Retinol)",
        .supplement_form = "Retinyl palmitate or preformed retinol (if poor converter)",
        .dose_range = "2500-5000 IU retinol/day (preformed, not beta-carotene)",
        .testing = "Serum retinol, retinol-binding protein",
        .genes = nut_vitamin_a_genes,
        .ngenes = 1,
        .food_sources = "Liver, egg yolks, dairy (preformed); carrots, sweet potato (provitamin A)",
    },
};
const size_t GH_NUTRIENT_PROFILE_COUNT = sizeof(GH_NUTRIENT_PROFILES) / sizeof(GH_NUTRIENT_PROFILES[0]);

const gh_mental_snp GH_MENTAL_SNPS[] = {
    {"rs6295", "HTR1A", "depression", 'G', "5-HT1A receptor (C-1019G) \342\200\224 reduced serotonin autoreceptor feedback", "GG genotype associated with increased depression risk and SSRI resistance", "Lemonde et al. 2003 (J Neurosci)"},
    {"rs1800532", "TPH1", "depression", 'T', "Tryptophan hydroxylase 1 \342\200\224 serotonin synthesis rate-limiting enzyme", "A allele associated with reduced serotonin synthesis and depression risk", "Zill et al. 2004 (Mol Psychiatry)"},
    {"rs110402", "CRHR1", "anxiety", 'A', "Corticotropin-releasing hormone receptor 1 \342\200\224 HPA axis regulation", "Modulates cortisol stress response; A allele may be protective post-trauma", "Bradley et al. 2008 (Arch Gen Psychiatry)"},
    {"rs9296158", "FKBP5", "anxiety", 'A', "FK506-binding protein 5 \342\200\224 glucocorticoid receptor sensitivity", "A allele associated with impaired cortisol recovery after stress", "Binder et al. 2008 (JAMA)"},
    {"rs279858", "GABRA2", "addiction", 'C', "GABA-A receptor alpha-2 subunit \342\200\224 inhibitory neurotransmission", "G allele associated with alcohol dependence and externalizing behavior", "Edenberg et al. 2004 (Am J Hum Genet)"},
    {"rs16969968", "CHRNA5", "addiction", 'A', "Nicotinic receptor alpha-5 \342\200\224 nicotine sensitivity", "A allele increases nicotine dependence risk and cigarettes/day", "Saccone et al. 2007 (Hum Mol Genet)"},
    {"rs1611115", "DBH", "adhd", 'T', "Dopamine beta-hydroxylase \342\200\224 converts dopamine to norepinephrine", "T allele reduces DBH activity; associated with ADHD traits", "Cubells et al. 2011 (Am J Med Genet B)"},
};
const size_t GH_MENTAL_SNP_COUNT = sizeof(GH_MENTAL_SNPS) / sizeof(GH_MENTAL_SNPS[0]);

static const char *const mh_depression_BDNF_statuses[] = {
    "reduced",
    "met_carrier",
};
static const char *const mh_depression_SLC6A4_statuses[] = {
    "short",
    "reduced",
};
static const char *const mh_depression_MTHFR_statuses[] = {
    "reduced",
    "severely_reduced",
};
static const char *const mh_depression_TNF_statuses[] = {
    "high",
    "elevated",
};
static const char *const mh_depression_IL6_statuses[] = {
    "high",
    "elevated",
};
static const gh_mental_gene mh_depression_genes[] = {
    {"BDNF", "Reduced neuroplasticity and BDNF secretion", mh_depression_BDNF_statuses, 2},
    {"SLC6A4", "Reduced serotonin reuptake transporter efficiency", mh_depression_SLC6A4_statuses, 2},
    {"MTHFR", "Impaired methylation affects neurotransmitter synthesis", mh_depression_MTHFR_statuses, 2},
    {"TNF", "Neuroinflammation linked to treatment-resistant depression", mh_depression_TNF_statuses, 2},
    {"IL6", "Inflammatory cytokine elevation drives sickness behavior/anhedonia", mh_depression_IL6_statuses, 2},
};
static const char *const mh_anxiety_COMT_statuses[] = {
    "slow",
};
static const char *const mh_anxiety_ADORA2A_statuses[] = {
    "anxiety_prone",
};
static const gh_mental_gene mh_anxiety_genes[] = {
    {"COMT", "Elevated prefrontal catecholamines increase anxiety proneness", mh_anxiety_COMT_statuses, 1},
    {"ADORA2A", "Caffeine-induced anxiety sensitivity", mh_anxiety_ADORA2A_statuses, 1},
};
static const char *const mh_addiction_ANKK1_statuses[] = {
    "risk",
    "reduced",
};
static const char *const mh_addiction_OPRM1_statuses[] = {
    "reduced",
    "altered",
};
static const char *const mh_addiction_ALDH2_statuses[] = {
    "reduced",
    "non_functional",
};
static const char *const mh_addiction_ADH1B_statuses[] = {
    "fast",
};
static const gh_mental_gene mh_addiction_genes[] = {
    {"ANKK1", "Reduced DRD2 density \342\200\224 reward deficiency, addiction vulnerability", mh_addiction_ANKK1_statuses, 2},
    {"OPRM1", "Altered opioid receptor sensitivity", mh_addiction_OPRM1_statuses, 2},
    {"ALDH2", "Alcohol flush reaction \342\200\224 protective against alcoholism", mh_addiction_ALDH2_statuses, 2},
    {"ADH1B", "Fast alcohol metabolism \342\200\224 modestly protective", mh_addiction_ADH1B_statuses, 1},
};
static const char *const mh_cognitive_COMT_statuses[] = {
    "slow",
};
static const char *const mh_cognitive_BDNF_statuses[] = {
    "reduced",
    "met_carrier",
};
static const gh_mental_gene mh_cognitive_genes[] = {
    {"COMT", "Higher prefrontal dopamine \342\200\224 better working memory but stress sensitivity", mh_cognitive_COMT_statuses, 1},
    {"BDNF", "Reduced learning-dependent BDNF release", mh_cognitive_BDNF_statuses, 2},
};

const gh_mental_domain GH_MENTAL_DOMAINS[] = {
    {"depression", mh_depression_genes, 5},
    {"anxiety", mh_anxiety_genes, 2},
    {"addiction", mh_addiction_genes, 4},
    {"cognitive", mh_cognitive_genes, 2},
};
const size_t GH_MENTAL_DOMAIN_COUNT = sizeof(GH_MENTAL_DOMAINS) / sizeof(GH_MENTAL_DOMAINS[0]);

const gh_longevity_snp GH_LONGEVITY_SNPS[] = {
    {"rs2802292", "FOXO3", "Forkhead box O3 \342\200\224 autophagy & longevity", 'G', "Willcox et al. 2008 (PNAS)"},
    {"rs5882", "CETP", "Cholesteryl ester transfer protein \342\200\224 HDL & longevity", 'G', "Barzilai et al. 2003 (JAMA)"},
    {"rs429358", "APOE", "APOE e4 allele \342\200\224 Alzheimer's & cardiovascular risk", 'T', "Deelen et al. 2011 (Aging Cell)"},
    {"rs1042522", "TP53", "Tumor protein p53 \342\200\224 cancer surveillance", 'G', "Bojesen & Nordestgaard 2008 (Cell)"},
    {"rs4880", "SOD2", "Superoxide dismutase \342\200\224 oxidative stress defense", 'A', "Soerensen et al. 2012 (Mech Ageing Dev)"},
    {"rs2536", "MTOR", "Mechanistic target of rapamycin \342\200\224 growth/aging pathway", 'C', "Johnson et al. 2013 (Nature)"},
    {"rs7069102", "SIRT1", "Sirtuin 1 \342\200\224 NAD+ deacetylase, caloric restriction pathway", 'G', "Figarska et al. 2013 (Age)"},
    {"rs9536314", "KLOTHO", "Klotho \342\200\224 anti-aging hormone, kidney & brain protection", 'T', "Arking et al. 2002 (PNAS)"},
    {"rs2229765", "IGF1R", "IGF-1 receptor \342\200\224 growth hormone/insulin pathway", 'A', "Suh et al. 2008 (PNAS)"},
    {"rs10936599", "TERC", "Telomerase RNA component \342\200\224 telomere maintenance", 'C', "Codd et al. 2013 (Nature Genetics)"},
    {"rs2736100", "TERT", "Telomerase reverse transcriptase \342\200\224 telomere length", 'C', "Codd et al. 2013 (Nature Genetics)"},
};
const size_t GH_LONGEVITY_SNP_COUNT = sizeof(GH_LONGEVITY_SNPS) / sizeof(GH_LONGEVITY_SNPS[0]);

static const char *const lg_cardiovascular_genes[] = {
    "APOE",
    "CETP",
    "AGT",
    "ACE",
    "AGTR1",
    "F5",
    "F2",
    "MTHFR",
};
static const char *const lg_cardiovascular_protective[] = {
    "longevity",
    "protective",
    "reference",
    "normal",
    "optimal",
};
static const char *const lg_cardiovascular_risk[] = {
    "e4_e4",
    "severely_reduced",
    "high_risk",
    "reduced",
    "heterozygous",
    "elevated",
    "e3_e4",
    "high",
    "homozygous",
};
static const char *const lg_metabolic_genes[] = {
    "FTO",
    "TCF7L2",
    "PPARG",
    "PPARA",
    "PPARGC1A",
    "MTNR1B",
};
static const char *const lg_metabolic_protective[] = {
    "normal",
    "protective",
    "reference",
};
static const char *const lg_metabolic_risk[] = {
    "reduced",
    "slow",
    "high_risk",
    "risk",
};
static const char *const lg_neurological_genes[] = {
    "APOE",
    "BDNF",
    "COMT",
    "ANKK1",
};
static const char *const lg_neurological_protective[] = {
    "fast",
    "optimal",
    "normal",
    "protective",
};
static const char *const lg_neurological_risk[] = {
    "reduced",
    "e3_e4",
    "met_carrier",
    "e4_e4",
    "slow",
    "risk",
};
static const char *const lg_inflammation_genes[] = {
    "TNF",
    "IL6",
    "SOD2",
    "GSTP1",
};
static const char *const lg_inflammation_protective[] = {
    "low",
    "normal",
    "protective",
    "reference",
};
static const char *const lg_inflammation_risk[] = {
    "reduced",
    "slow",
    "high",
    "elevated",
};
static const char *const lg_cancer_defense_genes[] = {
    "TP53",
    "SOD2",
    "NAT2",
    "GSTP1",
};
static const char *const lg_cancer_defense_protective[] = {
    "fast",
    "normal",
    "protective",
};
static const char *const lg_cancer_defense_risk[] = {
    "reduced",
    "slow",
    "risk",
};

const gh_healthspan_domain GH_HEALTHSPAN_DOMAINS[] = {
    {
        .name = "cardiovascular",
        .genes = lg_cardiovascular_genes,
        .ngenes = 8,
        .protective_statuses = lg_cardiovascular_protective,
        .nprotective_statuses = 5,
        .risk_statuses = lg_cardiovascular_risk,
        .nrisk_statuses = 9,
    },
    {
        .name = "metabolic",
        .genes = lg_metabolic_genes,
        .ngenes = 6,
        .protective_statuses = lg_metabolic_protective,
        .nprotective_statuses = 3,
        .risk_statuses = lg_metabolic_risk,
        .nrisk_statuses = 4,
    },
    {
        .name = "neurological",
        .genes = lg_neurological_genes,
        .ngenes = 4,
        .protective_statuses = lg_neurological_protective,
        .nprotective_statuses = 4,
        .risk_statuses = lg_neurological_risk,
        .nrisk_statuses = 6,
    },
    {
        .name = "inflammation",
        .genes = lg_inflammation_genes,
        .ngenes = 4,
        .protective_statuses = lg_inflammation_protective,
        .nprotective_statuses = 4,
        .risk_statuses = lg_inflammation_risk,
        .nrisk_statuses = 4,
    },
    {
        .name = "cancer_defense",
        .genes = lg_cancer_defense_genes,
        .ngenes = 4,
        .protective_statuses = lg_cancer_defense_protective,
        .nprotective_statuses = 3,
        .risk_statuses = lg_cancer_defense_risk,
        .nrisk_statuses = 3,
    },
};
const size_t GH_HEALTHSPAN_DOMAIN_COUNT = sizeof(GH_HEALTHSPAN_DOMAINS) / sizeof(GH_HEALTHSPAN_DOMAINS[0]);

