/* Generated by c/tools/gen_epistasis_data.py -- do not edit by hand.
 * Source: genetic_health/epistasis.py
 */

#include "gh_epistasis.h"

#include <stddef.h>

const gh_status_severity GH_STATUS_SEVERITY[] = {
    {"severely_reduced", 1.0},
    {"reduced", 0.5},
    {"slow", 1.0},
    {"intermediate", 0.5},
    {"anxiety_prone", 0.8},
    {"high", 1.0},
    {"elevated", 0.7},
    {"e4_e4", 1.0},
    {"e3_e4", 0.5},
    {"high_risk", 1.0},
    {"risk", 0.5},
    {"met_carrier", 0.6},
    {"homozygous", 1.0},
    {"carrier", 0.5},
};
const size_t GH_STATUS_SEVERITY_COUNT = sizeof(GH_STATUS_SEVERITY) / sizeof(GH_STATUS_SEVERITY[0]);

static const char *const ep_mthfr_comt_methylation_0_MTHFR[] = {
    "reduced", "severely_reduced",
};
static const char *const ep_mthfr_comt_methylation_0_COMT[] = {
    "slow",
};
static const gh_epi_requirement ep_mthfr_comt_methylation_0_req[] = {
    {"MTHFR", ep_mthfr_comt_methylation_0_MTHFR, 2},
    {"COMT", ep_mthfr_comt_methylation_0_COMT, 1},
};
static const char *const ep_mthfr_comt_methylation_0_actions[] = {
    "Start methylfolate at LOW dose (200-400mcg) \342\200\224 slow COMT individuals may over-respond to methyl donors",
    "Prioritize magnesium glycinate (300-400mg) for COMT support",
    "Avoid combining high-dose methylfolate + methylB12 initially",
    "Stress management is critical \342\200\224 meditation, breathwork, sleep",
    "Monitor for irritability/anxiety when starting methyl supplements",
};
static const gh_epi_condition ep_mthfr_comt_methylation_conditions[] = {
    {
        .required = ep_mthfr_comt_methylation_0_req,
        .nrequired = 2,
        .effect = "Reduced folate conversion (MTHFR) combined with slow catecholamine clearance (COMT) creates a dual burden: impaired methylation AND catecholamine accumulation. This may amplify anxiety, stress sensitivity, and supplement sensitivity (especially methyl donors).",
        .risk_level = "high",
        .mechanism = "MTHFR reduces 5-MTHF production, the methyl donor for homocysteine-to-methionine conversion. COMT requires SAMe (from methionine) to degrade catecholamines. When both are impaired, methyl group supply is low AND demand is backed up.",
        .actions = ep_mthfr_comt_methylation_0_actions,
        .nactions = 5,
    },
};

static const char *const ep_mthfr_mtrr_methylation_0_MTHFR[] = {
    "reduced", "severely_reduced",
};
static const char *const ep_mthfr_mtrr_methylation_0_MTRR[] = {
    "reduced", "severely_reduced",
};
static const gh_epi_requirement ep_mthfr_mtrr_methylation_0_req[] = {
    {"MTHFR", ep_mthfr_mtrr_methylation_0_MTHFR, 2},
    {"MTRR", ep_mthfr_mtrr_methylation_0_MTRR, 2},
};
static const char *const ep_mthfr_mtrr_methylation_0_actions[] = {
    "Methylfolate (400-800mcg) + methylcobalamin (1000-5000mcg)",
    "Add riboflavin (B2) 25-50mg \342\200\224 cofactor for MTHFR enzyme",
    "Monitor homocysteine \342\200\224 target <10 \316\274mol/L",
    "Emphasize leafy greens, legumes, liver for dietary folate",
    "Consider TMG (trimethylglycine) as alternate methyl donor",
};
static const gh_epi_condition ep_mthfr_mtrr_methylation_conditions[] = {
    {
        .required = ep_mthfr_mtrr_methylation_0_req,
        .nrequired = 2,
        .effect = "Both arms of the methylation cycle are impaired: MTHFR reduces folate activation, MTRR impairs B12 recycling. Homocysteine may accumulate from two independent bottlenecks.",
        .risk_level = "high",
        .mechanism = "MTHFR converts folate to 5-MTHF. MTRR regenerates methylcobalamin, the cofactor for methionine synthase. When both are impaired, the methionine synthase reaction is doubly compromised.",
        .actions = ep_mthfr_mtrr_methylation_0_actions,
        .nactions = 5,
    },
};

static const char *const ep_caffeine_sensitivity_0_CYP1A2[] = {
    "slow", "intermediate",
};
static const char *const ep_caffeine_sensitivity_0_COMT[] = {
    "slow",
};
static const gh_epi_requirement ep_caffeine_sensitivity_0_req[] = {
    {"CYP1A2", ep_caffeine_sensitivity_0_CYP1A2, 2},
    {"COMT", ep_caffeine_sensitivity_0_COMT, 1},
};
static const char *const ep_caffeine_sensitivity_0_actions[] = {
    "Limit caffeine to <100mg/day (one small coffee) before 10am",
    "Consider switching to green tea (L-theanine counterbalances)",
    "Avoid caffeine entirely if experiencing anxiety or insomnia",
    "Allow 10+ hours caffeine clearance before sleep",
};
static const char *const ep_caffeine_sensitivity_1_CYP1A2[] = {
    "slow", "intermediate",
};
static const char *const ep_caffeine_sensitivity_1_ADORA2A[] = {
    "anxiety_prone",
};
static const gh_epi_requirement ep_caffeine_sensitivity_1_req[] = {
    {"CYP1A2", ep_caffeine_sensitivity_1_CYP1A2, 2},
    {"ADORA2A", ep_caffeine_sensitivity_1_ADORA2A, 1},
};
static const char *const ep_caffeine_sensitivity_1_actions[] = {
    "Strong caffeine sensitivity likely \342\200\224 consider elimination",
    "If consuming caffeine, maximum 50-100mg before 9am",
    "L-theanine (200mg) may help if caffeine is consumed",
};
static const gh_epi_condition ep_caffeine_sensitivity_conditions[] = {
    {
        .required = ep_caffeine_sensitivity_0_req,
        .nrequired = 2,
        .effect = "Slow caffeine metabolism (CYP1A2) combined with slow catecholamine clearance (COMT) means caffeine both stays in the body longer AND its stimulatory effects are amplified by delayed norepinephrine/dopamine breakdown.",
        .risk_level = "moderate",
        .mechanism = "CYP1A2 metabolizes caffeine in the liver. COMT degrades the catecholamines that caffeine stimulates. Slow variants in both create a double hit: more caffeine exposure AND more neurotransmitter accumulation.",
        .actions = ep_caffeine_sensitivity_0_actions,
        .nactions = 4,
    },
    {
        .required = ep_caffeine_sensitivity_1_req,
        .nrequired = 2,
        .effect = "Slow caffeine metabolism with anxiety-prone adenosine receptors: caffeine stays active longer AND triggers stronger anxiogenic response.",
        .risk_level = "moderate",
        .mechanism = "CYP1A2 prolongs caffeine half-life. ADORA2A variant increases anxiety response to adenosine receptor blockade by caffeine.",
        .actions = ep_caffeine_sensitivity_1_actions,
        .nactions = 3,
    },
};

static const char *const ep_blood_pressure_polygenic_0_ACE[] = {
    "elevated", "high",
};
static const char *const ep_blood_pressure_polygenic_0_AGT[] = {
    "elevated", "high",
};
static const gh_epi_requirement ep_blood_pressure_polygenic_0_req[] = {
    {"ACE", ep_blood_pressure_polygenic_0_ACE, 2},
    {"AGT", ep_blood_pressure_polygenic_0_AGT, 2},
};
static const char *const ep_blood_pressure_polygenic_0_actions[] = {
    "Home blood pressure monitoring (target <130/80)",
    "DASH diet \342\200\224 high potassium, low sodium (<2300mg/day)",
    "150+ minutes/week aerobic exercise",
    "Discuss ACE inhibitor suitability with physician if needed",
    "Limit alcohol, manage stress",
};
static const char *const ep_blood_pressure_polygenic_1_ACE[] = {
    "elevated", "high",
};
static const char *const ep_blood_pressure_polygenic_1_AGTR1[] = {
    "elevated", "high",
};
static const gh_epi_requirement ep_blood_pressure_polygenic_1_req[] = {
    {"ACE", ep_blood_pressure_polygenic_1_ACE, 2},
    {"AGTR1", ep_blood_pressure_polygenic_1_AGTR1, 2},
};
static const char *const ep_blood_pressure_polygenic_1_actions[] = {
    "Blood pressure monitoring essential",
    "Sodium restriction particularly important",
    "ARBs (angiotensin receptor blockers) may be especially effective",
    "Regular aerobic exercise \342\200\224 30+ min most days",
};
static const gh_epi_condition ep_blood_pressure_polygenic_conditions[] = {
    {
        .required = ep_blood_pressure_polygenic_0_req,
        .nrequired = 2,
        .effect = "Elevated ACE activity combined with elevated angiotensinogen production amplifies the renin-angiotensin system \342\200\224 substantially increases hypertension risk beyond either variant alone.",
        .risk_level = "high",
        .mechanism = "AGT produces angiotensinogen (the substrate). ACE converts it to angiotensin II (the vasoconstrictor). When both are elevated, more substrate AND more conversion = higher angiotensin II levels.",
        .actions = ep_blood_pressure_polygenic_0_actions,
        .nactions = 5,
    },
    {
        .required = ep_blood_pressure_polygenic_1_req,
        .nrequired = 2,
        .effect = "Elevated ACE activity combined with more sensitive angiotensin II receptor \342\200\224 more angiotensin II produced AND stronger vascular response to it.",
        .risk_level = "high",
        .mechanism = "ACE increases angiotensin II production. AGTR1 variant enhances receptor response. Combined effect on vasoconstriction is multiplicative.",
        .actions = ep_blood_pressure_polygenic_1_actions,
        .nactions = 4,
    },
};

static const char *const ep_apoe_mthfr_cardiovascular_0_APOE[] = {
    "e3_e4", "e4_e4",
};
static const char *const ep_apoe_mthfr_cardiovascular_0_MTHFR[] = {
    "reduced", "severely_reduced",
};
static const gh_epi_requirement ep_apoe_mthfr_cardiovascular_0_req[] = {
    {"APOE", ep_apoe_mthfr_cardiovascular_0_APOE, 2},
    {"MTHFR", ep_apoe_mthfr_cardiovascular_0_MTHFR, 2},
};
static const char *const ep_apoe_mthfr_cardiovascular_0_actions[] = {
    "Regular lipid panel (focus on LDL-C and apoB)",
    "Monitor homocysteine \342\200\224 target <10 \316\274mol/L",
    "Mediterranean diet (reduce saturated fat, increase omega-3)",
    "Exercise regularly \342\200\224 particularly beneficial for APOE e4",
    "Consider early statin discussion with physician if LDL elevated",
};
static const gh_epi_condition ep_apoe_mthfr_cardiovascular_conditions[] = {
    {
        .required = ep_apoe_mthfr_cardiovascular_0_req,
        .nrequired = 2,
        .effect = "APOE e4 increases LDL cholesterol and cardiovascular risk. Combined with MTHFR-driven elevated homocysteine, both lipid and homocysteine cardiovascular risk pathways are activated simultaneously.",
        .risk_level = "high",
        .mechanism = "APOE e4 impairs LDL receptor recycling (higher LDL). MTHFR reduces homocysteine clearance. Both are independent cardiovascular risk factors with potential synergy.",
        .actions = ep_apoe_mthfr_cardiovascular_0_actions,
        .nactions = 5,
    },
};

static const char *const ep_metabolic_risk_0_FTO[] = {
    "risk", "high_risk",
};
static const char *const ep_metabolic_risk_0_TCF7L2[] = {
    "risk", "high_risk",
};
static const gh_epi_requirement ep_metabolic_risk_0_req[] = {
    {"FTO", ep_metabolic_risk_0_FTO, 2},
    {"TCF7L2", ep_metabolic_risk_0_TCF7L2, 2},
};
static const char *const ep_metabolic_risk_0_actions[] = {
    "Weight management is particularly important",
    "Monitor fasting glucose and HbA1c annually",
    "Regular physical activity (improves insulin sensitivity)",
    "Emphasize low-glycemic-index foods",
    "Consider time-restricted eating if appropriate",
};
static const gh_epi_condition ep_metabolic_risk_conditions[] = {
    {
        .required = ep_metabolic_risk_0_req,
        .nrequired = 2,
        .effect = "FTO increases obesity susceptibility, TCF7L2 increases diabetes risk. Combined, the metabolic syndrome risk is amplified: weight gain tendency feeds directly into insulin resistance pathway.",
        .risk_level = "moderate",
        .mechanism = "FTO variants increase appetite/reduced satiety signaling. TCF7L2 impairs insulin secretion from beta cells. Excess weight (FTO) worsens insulin resistance, which compounds the TCF7L2-driven beta cell dysfunction.",
        .actions = ep_metabolic_risk_0_actions,
        .nactions = 5,
    },
};

static const char *const ep_bdnf_comt_stress_0_BDNF[] = {
    "reduced", "met_carrier",
};
static const char *const ep_bdnf_comt_stress_0_COMT[] = {
    "slow",
};
static const gh_epi_requirement ep_bdnf_comt_stress_0_req[] = {
    {"BDNF", ep_bdnf_comt_stress_0_BDNF, 2},
    {"COMT", ep_bdnf_comt_stress_0_COMT, 1},
};
static const char *const ep_bdnf_comt_stress_0_actions[] = {
    "Regular aerobic exercise is critical (strongest BDNF booster)",
    "Stress management: meditation, breathwork, adequate sleep",
    "Avoid chronic high-stress environments when possible",
    "Social connection supports BDNF signaling",
    "Consider mindfulness-based stress reduction (MBSR)",
};
static const gh_epi_condition ep_bdnf_comt_stress_conditions[] = {
    {
        .required = ep_bdnf_comt_stress_0_req,
        .nrequired = 2,
        .effect = "Reduced BDNF production (Met carrier) combined with slow COMT creates vulnerability to stress-related cognitive effects: less neuroplasticity reserve AND more catecholamine accumulation under stress.",
        .risk_level = "moderate",
        .mechanism = "BDNF Val66Met reduces activity-dependent BDNF secretion. COMT Val158Met (slow) reduces dopamine/norepinephrine degradation. Under stress, reduced BDNF impairs hippocampal function while excess catecholamines impair prefrontal function.",
        .actions = ep_bdnf_comt_stress_0_actions,
        .nactions = 5,
    },
};

static const char *const ep_iron_inflammation_0_HFE[] = {
    "carrier", "homozygous",
};
static const char *const ep_iron_inflammation_0_IL6[] = {
    "high",
};
static const gh_epi_requirement ep_iron_inflammation_0_req[] = {
    {"HFE", ep_iron_inflammation_0_HFE, 2},
    {"IL6", ep_iron_inflammation_0_IL6, 1},
};
static const char *const ep_iron_inflammation_0_actions[] = {
    "Monitor ferritin and CRP together (iron + inflammation)",
    "Consider regular blood donation if ferritin runs high",
    "Anti-inflammatory diet: omega-3, colorful vegetables",
    "Avoid iron supplements unless deficiency confirmed",
    "Vitamin C with meals increases iron absorption \342\200\224 moderate intake",
};
static const gh_epi_condition ep_iron_inflammation_conditions[] = {
    {
        .required = ep_iron_inflammation_0_req,
        .nrequired = 2,
        .effect = "HFE variant (iron accumulation tendency) combined with elevated IL-6 (inflammatory) creates a cycle: excess iron promotes inflammation, and inflammation alters iron distribution (hepcidin axis).",
        .risk_level = "moderate",
        .mechanism = "HFE mutations impair hepcidin response, allowing excess iron absorption. IL-6 variant increases baseline inflammation. Excess iron catalyzes reactive oxygen species (Fenton reaction), amplifying inflammatory damage.",
        .actions = ep_iron_inflammation_0_actions,
        .nactions = 5,
    },
};

const gh_epi_model GH_EPISTASIS_MODELS[] = {
    {"mthfr_comt_methylation", "MTHFR + COMT: Methylation-Catecholamine Interaction", ep_mthfr_comt_methylation_conditions, 1},
    {"mthfr_mtrr_methylation", "MTHFR + MTRR: Double Methylation Cycle Impairment", ep_mthfr_mtrr_methylation_conditions, 1},
    {"caffeine_sensitivity", "CYP1A2 + COMT + ADORA2A: Caffeine Sensitivity Triad", ep_caffeine_sensitivity_conditions, 2},
    {"blood_pressure_polygenic", "ACE + AGT + AGTR1: Blood Pressure Polygenic Risk", ep_blood_pressure_polygenic_conditions, 2},
    {"apoe_mthfr_cardiovascular", "APOE e4 + MTHFR: Cardiovascular Risk Interaction", ep_apoe_mthfr_cardiovascular_conditions, 1},
    {"metabolic_risk", "FTO + TCF7L2: Metabolic Syndrome Risk", ep_metabolic_risk_conditions, 1},
    {"bdnf_comt_stress", "BDNF + COMT: Stress Response Interaction", ep_bdnf_comt_stress_conditions, 1},
    {"iron_inflammation", "HFE + IL6: Iron-Inflammation Interaction", ep_iron_inflammation_conditions, 1},
};
const size_t GH_EPISTASIS_MODEL_COUNT = sizeof(GH_EPISTASIS_MODELS) / sizeof(GH_EPISTASIS_MODELS[0]);

