/* Generated by c/tools/gen_insights_data.py -- do not edit by hand.
 * Source: genetic_health/insights.py
 */

#include "gh_insights.h"

#include <stddef.h>

static const gh_insight_entry sgi_CYP2C9_intermediate[] = {
    {"CYP2C9 intermediate metabolism and warfarin sensitivity", "CYP2C9 *1/*2 carriers require ~20% lower warfarin doses on average. The *2 allele reduces enzyme activity to ~12% of normal for that copy, slowing metabolism of S-warfarin, NSAIDs like ibuprofen, and phenytoin.", "Johnson et al. 2017, Clin Pharmacol Ther, PMID: 28198005", "If prescribed warfarin, your genotype predicts lower dose requirements. Standard starting doses may cause over-anticoagulation. NSAIDs should be used at the lowest effective dose."},
};
static const gh_insight_entry sgi_CYP2C9_poor[] = {
    {"CYP2C9 poor metabolism \342\200\224 significant drug impact", "CYP2C9 poor metabolizers have substantially reduced clearance of warfarin, NSAIDs, and several other drugs. Warfarin dose reductions of 30-50% are typical.", "Johnson et al. 2017, Clin Pharmacol Ther, PMID: 28198005", "This is a clinically significant finding. Carry a pharmacogenomic card listing your CYP2C9 status for any prescribing encounter."},
};
static const gh_insight_entry sgi_DPYD_intermediate[] = {
    {"DPYD and fluoropyrimidine chemotherapy safety", "DPYD encodes dihydropyrimidine dehydrogenase, which metabolizes >80% of 5-FU. Intermediate metabolizers have increased risk of severe toxicity (grade 3-4) from standard-dose fluoropyrimidines.", "Meulendijks et al. 2015, J Clin Oncol, PMID: 29152729", "If you ever need 5-FU or capecitabine chemotherapy, your oncologist should start at 50% dose and titrate up based on tolerance. Pre-treatment DPYD testing is now recommended by CPIC guidelines."},
};
static const gh_insight_entry sgi_DPYD_poor[] = {
    {"DPYD deficiency \342\200\224 critical pharmacogenomic finding", "DPYD poor metabolizers are at high risk of life-threatening toxicity from fluoropyrimidine chemotherapy. Standard doses can cause fatal myelosuppression and mucositis.", "Meulendijks et al. 2015, J Clin Oncol, PMID: 29152729", "Fluoropyrimidines (5-FU, capecitabine) should be avoided or used at drastically reduced doses with extreme caution. Ensure this is in your medical record."},
};
static const gh_insight_entry sgi_CYP1A2_slow[] = {
    {"Slow caffeine metabolism and cardiovascular risk", "Slow CYP1A2 metabolizers who drink 2+ cups of coffee/day have a significantly increased risk of myocardial infarction compared to fast metabolizers. Caffeine half-life is ~8-10 hours vs ~4 hours.", "Cornelis et al. 2006, JAMA, PMID: 16522833", "Limiting coffee to 1 cup/day before 10am is prudent. Afternoon caffeine will still be circulating at bedtime, disrupting sleep architecture even if you fall asleep fine."},
};
static const gh_insight_entry sgi_CYP1A2_intermediate[] = {
    {"Moderate caffeine metabolism", "Intermediate CYP1A2 metabolizers clear caffeine at a moderate rate (half-life ~5-6 hours). The cardiovascular risk from coffee is intermediate between slow and fast metabolizers.", "Cornelis et al. 2006, JAMA, PMID: 16522833", "Moderate caffeine intake (1-2 cups before early afternoon) is reasonable. Pay attention to sleep quality as a personal barometer."},
};
static const gh_insight_entry sgi_APOE_e2_carrier[] = {
    {"APOE e2 and cardiovascular protection", "APOE e2 carriers have ~20% lower LDL cholesterol on average and reduced risk of coronary artery disease. The e2 allele is associated with enhanced clearance of atherogenic lipoproteins.", "Bennet et al. 2007, J Biol Chem, PMID: 17142461", "Your e2 allele is associated with favorable lipid profiles. This is a protective finding, though standard cardiovascular prevention still applies."},
    {"APOE e2 and reduced Alzheimer's risk", "APOE e2 carriers have roughly half the Alzheimer's disease risk compared to the common e3/e3 genotype. The e2 allele is associated with less amyloid-beta aggregation.", "Corder et al. 1994, Nat Genet, PMID: 7894489", "This is protective but not absolute. Maintain cardiovascular health, regular exercise, quality sleep, and cognitive engagement \342\200\224 all of which further reduce dementia risk."},
};
static const gh_insight_entry sgi_CETP_favorable[] = {
    {"CETP I405V and longevity association", "The CETP I405V variant (VV genotype) is associated with larger HDL particle size, higher HDL cholesterol, and was significantly enriched in Ashkenazi Jewish centenarians.", "Barzilai et al. 2003, JAMA, PMID: 18235225", "This is a favorable variant associated with cardiovascular protection and longevity. Support with a heart-healthy lifestyle."},
};
static const gh_insight_entry sgi_CETP_highly_favorable[] = {
    {"CETP homozygous longevity variant", "Homozygous CETP I405V carriers have the strongest association with elevated HDL particle size and longevity. This genotype was found at 2-3x higher frequency in centenarians.", "Barzilai et al. 2003, JAMA, PMID: 18235225", "This is one of the strongest single-gene longevity signals. Your lipid profile likely trends favorable."},
};
static const gh_insight_entry sgi_AGTR1_increased[] = {
    {"AGTR1 and angiotensin receptor blocker response", "The AGTR1 A1166C variant is associated with enhanced angiotensin II receptor activity and hypertension. Carriers show particularly good blood pressure response to ARBs (losartan, valsartan, irbesartan).", "Bonnardeaux et al. 1994, Hypertension, PMID: 16129819", "If you need blood pressure medication, ARBs target the exact receptor your variant overactivates \342\200\224 a genetically informed choice."},
};
static const gh_insight_entry sgi_ACE_high[] = {
    {"ACE I/D polymorphism and exercise blood pressure response", "The ACE DD genotype is associated with higher ACE activity, greater exercise-induced blood pressure rise, but also better strength/power performance. Regular aerobic exercise reduces the BP impact.", "Myerson et al. 1999, J Appl Physiol, PMID: 10973849", "Consistent aerobic exercise is especially important for your genotype. If medication is needed, ACE inhibitors target your specific pathway."},
};
static const gh_insight_entry sgi_GC_low[] = {
    {"GC variants and vitamin D status at different latitudes", "GC encodes vitamin D binding protein. Your variant reduces circulating 25-OH vitamin D levels. At latitudes above ~35N (e.g. most of the US, Europe), winter UVB is insufficient, compounding genetic predisposition.", "Wang et al. 2010, Lancet, PMID: 20541252", "Supplement vitamin D3 (2,000-5,000 IU/day) year-round, especially in winter. Target 40-60 ng/mL. Take with a fat-containing meal."},
};
static const gh_insight_entry sgi_PEMT_reduced[] = {
    {"PEMT and dietary choline requirements", "PEMT creates phosphatidylcholine using SAMe as a methyl donor. Reduced PEMT function increases dietary choline needs. 75% of the population does not meet adequate intake for choline (550mg men, 425mg women).", "da Costa et al. 2006, Am J Clin Nutr, PMID: 17510091", "Prioritize choline-rich foods: eggs (147mg/egg), beef liver (356mg/3oz), salmon, chicken. Choline is critical for liver health, brain function, and cell membranes."},
};
static const gh_insight_entry sgi_PEMT_significantly_reduced[] = {
    {"PEMT homozygous \342\200\224 high choline dependency", "Homozygous PEMT variants substantially reduce endogenous phosphatidylcholine synthesis. This genotype developed organ dysfunction on low-choline diets in clinical studies.", "da Costa et al. 2006, Am J Clin Nutr, PMID: 17510091", "Dietary choline is essential for you. Consider supplementation (CDP-choline 250-500mg) if dietary intake is insufficient. Particularly important during pregnancy."},
};
static const gh_insight_entry sgi_BCMO1_reduced[] = {
    {"BCMO1 and beta-carotene conversion efficiency", "BCMO1 converts plant beta-carotene to retinol (vitamin A). Your variant reduces conversion efficiency by ~30-70%. Relying solely on plant carotenoids for vitamin A may lead to subclinical deficiency.", "Leung et al. 2009, FASEB J, PMID: 19103647", "Include preformed vitamin A sources: eggs, liver, dairy, fatty fish. Don't rely on carrots and sweet potatoes alone for vitamin A."},
};
static const gh_insight_entry sgi_ACTN3_endurance[] = {
    {"ACTN3 R577X and muscle fiber composition", "ACTN3 XX genotype means absence of alpha-actinin-3 in fast-twitch muscle fibers. This shifts muscle composition toward slow-twitch (endurance). XX is found in ~18% of Europeans but is rare in elite sprinters.", "Yang et al. 2003, Am J Hum Genet, PMID: 18043716", "Your genetics favor endurance over sprint/power activities. You may find you excel at distance running, cycling, or swimming. Strength training still builds muscle, just with a different fiber emphasis."},
};
static const gh_insight_entry sgi_ACTN3_power[] = {
    {"ACTN3 RR and sprint/power performance", "ACTN3 RR genotype preserves full alpha-actinin-3 in fast-twitch fibers. This genotype is over-represented in elite sprinters and power athletes across multiple populations.", "Yang et al. 2003, Am J Hum Genet, PMID: 18043716", "Your fast-twitch fiber composition favors explosive activities. Include plyometrics, sprints, and heavy compound lifts."},
};
static const gh_insight_entry sgi_ACTN3_mixed[] = {
    {"ACTN3 heterozygous \342\200\224 versatile muscle profile", "ACTN3 RX gives a balanced fast/slow-twitch fiber mix. Heterozygotes can develop either power or endurance based on training focus.", "Yang et al. 2003, Am J Hum Genet, PMID: 18043716", "You have the most versatile muscle genetics \342\200\224 adapt training to your goals. Both strength and endurance respond well."},
};
static const gh_insight_entry sgi_HFE_carrier[] = {
    {"HFE H63D and iron regulation", "HFE H63D is a common variant (~15% carrier frequency in Europeans) that mildly increases iron absorption. Alone it rarely causes clinical hemochromatosis, but iron can accumulate over decades.", "Feder et al. 1996, Nat Genet; EASL Guidelines, PMID: 20471131", "Monitor ferritin every 1-2 years. Avoid iron supplements unless deficiency is confirmed. Regular blood donation helps regulate iron."},
};
static const gh_insight_entry sgi_TAS2R38_non_taster[] = {
    {"TAS2R38 non-taster and food preferences", "TAS2R38 non-tasters cannot detect bitter compounds (PTC/PROP) in cruciferous vegetables. This may reduce aversion to bitter greens but is also associated with higher preference for sweet/salty foods.", "Kim et al. 2003, Science, PMID: 16051168", "You likely find broccoli, kale, and Brussels sprouts palatable. Be mindful of the tendency toward sweet/salty preferences."},
};
static const gh_insight_entry sgi_MC1R_accelerated[] = {
    {"MC1R variants and perceived age", "MC1R variants are associated with looking ~2 years older than chronological age, independent of sun exposure and skin color. The effect is mediated through melanin pathway impacts on skin structure.", "Liu et al. 2016, Curr Biol, PMID: 27189542", "Consistent sun protection (SPF 30+) and topical retinoids can partially offset the photoaging acceleration."},
};
static const gh_insight_entry sgi_ADH1B_slow[] = {
    {"ADH1B and alcohol metabolism patterns", "ADH1B slow metabolizers convert alcohol to acetaldehyde more slowly. Alcohol effects last longer per drink. This is distinct from the ALDH2 'Asian flush' variant.", "Edenberg 2007, Alcohol Res Health, PMID: 17718403", "Pace drinks more slowly. Effects persist longer, so factor timing into driving and next-day planning."},
};
static const gh_insight_entry sgi_ADH1B_fast[] = {
    {"ADH1B fast metabolism and alcohol response", "ADH1B fast metabolizers rapidly convert alcohol to acetaldehyde. This can cause flushing and nausea with alcohol, which is actually protective against alcohol use disorder.", "Edenberg 2007, Alcohol Res Health, PMID: 17718403", "Your aversive response to alcohol is genetically protective. Don't push through discomfort \342\200\224 it's a signal."},
};
static const gh_insight_entry sgi_MTHFR_reduced[] = {
    {"MTHFR C677T heterozygous and folate metabolism", "One copy of C677T reduces MTHFR enzyme activity by ~35%. This is very common (~40% of many populations carry at least one copy) and has modest effects on homocysteine that are easily managed.", "Frosst et al. 1995, Nat Genet; Klerk et al. 2002, PMID: 12145525", "Use methylfolate (5-MTHF) instead of folic acid when supplementing. Eat folate-rich foods: leafy greens, legumes, citrus."},
};
static const gh_insight_entry sgi_MTHFR_significantly_reduced[] = {
    {"MTHFR C677T homozygous \342\200\224 70% reduced activity", "Homozygous C677T reduces MTHFR activity by ~70%, significantly impairing conversion of folic acid to the active 5-MTHF form. Homocysteine levels are typically elevated without intervention.", "Frosst et al. 1995, Nat Genet; Klerk et al. 2002, PMID: 12145525", "Methylfolate supplementation (400-800mcg) is recommended. Monitor homocysteine levels. Avoid synthetic folic acid in fortified foods."},
};
static const gh_insight_entry sgi_HLA_DQA1_increased_risk[] = {
    {"HLA-DQ2.5 and celiac disease susceptibility", "HLA-DQ2.5 is present in ~95% of celiac patients, but only ~3% of carriers develop the disease. It is necessary but not sufficient.", "Sollid et al. 1989, J Exp Med; Lundin et al. 2015", "No need for preventive gluten-free diet. If GI symptoms, fatigue, or unexplained iron deficiency develop, request tTG-IgA testing while still eating gluten."},
};
static const gh_insight_entry sgi_COMT_slow[] = {
    {"COMT Val158Met and stress-cognition tradeoff", "Slow COMT (Met/Met) provides higher baseline dopamine in prefrontal cortex \342\200\224 better working memory and focus in calm conditions, but vulnerability to stress-induced cognitive decline (the 'worrier' vs 'warrior' model).", "Egan et al. 2001, PNAS, PMID: 11381111", "Leverage calm-state cognitive advantages. Build robust stress management (meditation, exercise). Stimulants have amplified effects."},
};
static const gh_insight_entry sgi_COMT_fast[] = {
    {"COMT Val/Val \342\200\224 the 'warrior' genotype", "Fast COMT rapidly clears dopamine and catecholamines. This provides stress resilience and steady performance under pressure, but lower baseline prefrontal dopamine in calm conditions.", "Egan et al. 2001, PNAS, PMID: 11381111", "You perform well under pressure. May benefit from mild stimulants (caffeine) for focus during routine tasks."},
};

const gh_single_gene_insight GH_SINGLE_GENE_INSIGHTS[] = {
    {"CYP2C9", "intermediate", sgi_CYP2C9_intermediate, 1},
    {"CYP2C9", "poor", sgi_CYP2C9_poor, 1},
    {"DPYD", "intermediate", sgi_DPYD_intermediate, 1},
    {"DPYD", "poor", sgi_DPYD_poor, 1},
    {"CYP1A2", "slow", sgi_CYP1A2_slow, 1},
    {"CYP1A2", "intermediate", sgi_CYP1A2_intermediate, 1},
    {"APOE", "e2_carrier", sgi_APOE_e2_carrier, 2},
    {"CETP", "favorable", sgi_CETP_favorable, 1},
    {"CETP", "highly_favorable", sgi_CETP_highly_favorable, 1},
    {"AGTR1", "increased", sgi_AGTR1_increased, 1},
    {"ACE", "high", sgi_ACE_high, 1},
    {"GC", "low", sgi_GC_low, 1},
    {"PEMT", "reduced", sgi_PEMT_reduced, 1},
    {"PEMT", "significantly_reduced", sgi_PEMT_significantly_reduced, 1},
    {"BCMO1", "reduced", sgi_BCMO1_reduced, 1},
    {"ACTN3", "endurance", sgi_ACTN3_endurance, 1},
    {"ACTN3", "power", sgi_ACTN3_power, 1},
    {"ACTN3", "mixed", sgi_ACTN3_mixed, 1},
    {"HFE", "carrier", sgi_HFE_carrier, 1},
    {"TAS2R38", "non_taster", sgi_TAS2R38_non_taster, 1},
    {"MC1R", "accelerated", sgi_MC1R_accelerated, 1},
    {"ADH1B", "slow", sgi_ADH1B_slow, 1},
    {"ADH1B", "fast", sgi_ADH1B_fast, 1},
    {"MTHFR", "reduced", sgi_MTHFR_reduced, 1},
    {"MTHFR", "significantly_reduced", sgi_MTHFR_significantly_reduced, 1},
    {"HLA-DQA1", "increased_risk", sgi_HLA_DQA1_increased_risk, 1},
    {"COMT", "slow", sgi_COMT_slow, 1},
    {"COMT", "fast", sgi_COMT_fast, 1},
};
const size_t GH_SINGLE_GENE_INSIGHT_COUNT = sizeof(GH_SINGLE_GENE_INSIGHTS) / sizeof(GH_SINGLE_GENE_INSIGHTS[0]);

static const char *const mgn_bp_cluster_r_AGTR1[] = {
    "elevated", "increased",
};
static const char *const mgn_bp_cluster_r_ACE[] = {
    "high",
};
static const gh_gene_match mgn_bp_cluster_required_genes[] = {
    {"AGTR1", mgn_bp_cluster_r_AGTR1, 2},
    {"ACE", mgn_bp_cluster_r_ACE, 1},
};
static const char *const mgn_bp_cluster_o_AGT[] = {
    "increased",
};
static const char *const mgn_bp_cluster_o_GNB3[] = {
    "increased",
};
static const char *const mgn_bp_cluster_o_ADRB1[] = {
    "arg389",
};
static const gh_gene_match mgn_bp_cluster_optional_genes[] = {
    {"AGT", mgn_bp_cluster_o_AGT, 1},
    {"GNB3", mgn_bp_cluster_o_GNB3, 1},
    {"ADRB1", mgn_bp_cluster_o_ADRB1, 1},
};
static const char *const mgn_bp_cluster_refs[] = {
    "Bonnardeaux et al. 1994, Hypertension, PMID: 8021009",
    "Rigat et al. 1990, J Clin Invest, PMID: 10973849",
};

static const char *const mgn_caffeine_profile_r_CYP1A2[] = {
    "slow", "intermediate",
};
static const gh_gene_match mgn_caffeine_profile_required_genes[] = {
    {"CYP1A2", mgn_caffeine_profile_r_CYP1A2, 2},
};
static const char *const mgn_caffeine_profile_o_COMT[] = {
    "slow",
};
static const char *const mgn_caffeine_profile_o_ADORA2A[] = {
    "anxiety_prone",
};
static const gh_gene_match mgn_caffeine_profile_optional_genes[] = {
    {"COMT", mgn_caffeine_profile_o_COMT, 1},
    {"ADORA2A", mgn_caffeine_profile_o_ADORA2A, 1},
};
static const char *const mgn_caffeine_profile_refs[] = {
    "Cornelis et al. 2006, JAMA, PMID: 16522833",
};

static const char *const mgn_methylation_choline_r_PEMT[] = {
    "reduced", "significantly_reduced",
};
static const gh_gene_match mgn_methylation_choline_required_genes[] = {
    {"PEMT", mgn_methylation_choline_r_PEMT, 2},
};
static const char *const mgn_methylation_choline_o_MTHFR[] = {
    "reduced", "significantly_reduced",
};
static const char *const mgn_methylation_choline_o_MTRR[] = {
    "reduced", "significantly_reduced",
};
static const char *const mgn_methylation_choline_o_COMT[] = {
    "slow",
};
static const gh_gene_match mgn_methylation_choline_optional_genes[] = {
    {"MTHFR", mgn_methylation_choline_o_MTHFR, 2},
    {"MTRR", mgn_methylation_choline_o_MTRR, 2},
    {"COMT", mgn_methylation_choline_o_COMT, 1},
};
static const char *const mgn_methylation_choline_refs[] = {
    "da Costa et al. 2006, Am J Clin Nutr, PMID: 17510091",
    "Frosst et al. 1995, Nat Genet, PMID: 12145525",
};

static const char *const mgn_iron_profile_r_HFE[] = {
    "carrier", "at_risk", "high_risk",
};
static const gh_gene_match mgn_iron_profile_required_genes[] = {
    {"HFE", mgn_iron_profile_r_HFE, 3},
};
static const char *const mgn_iron_profile_refs[] = {
    "EASL Clinical Practice Guidelines, PMID: 20471131",
};

static const char *const mgn_cardiovascular_lipids_r_CETP[] = {
    "favorable", "highly_favorable",
};
static const gh_gene_match mgn_cardiovascular_lipids_required_genes[] = {
    {"CETP", mgn_cardiovascular_lipids_r_CETP, 2},
};
static const char *const mgn_cardiovascular_lipids_o_APOE[] = {
    "e2_carrier", "protective",
};
static const char *const mgn_cardiovascular_lipids_o_APOA2[] = {
    "sensitive",
};
static const gh_gene_match mgn_cardiovascular_lipids_optional_genes[] = {
    {"APOE", mgn_cardiovascular_lipids_o_APOE, 2},
    {"APOA2", mgn_cardiovascular_lipids_o_APOA2, 1},
};
static const char *const mgn_cardiovascular_lipids_refs[] = {
    "Barzilai et al. 2003, JAMA, PMID: 18235225",
};

static const char *const mgn_vitamin_d_profile_r_GC[] = {
    "low",
};
static const gh_gene_match mgn_vitamin_d_profile_required_genes[] = {
    {"GC", mgn_vitamin_d_profile_r_GC, 1},
};
static const char *const mgn_vitamin_d_profile_o_BCMO1[] = {
    "reduced",
};
static const gh_gene_match mgn_vitamin_d_profile_optional_genes[] = {
    {"BCMO1", mgn_vitamin_d_profile_o_BCMO1, 1},
};
static const char *const mgn_vitamin_d_profile_refs[] = {
    "Wang et al. 2010, Lancet, PMID: 20541252",
};

static const char *const mgn_skin_aging_r_MC1R[] = {
    "accelerated", "fair_skin", "red_hair", "high_risk",
};
static const gh_gene_match mgn_skin_aging_required_genes[] = {
    {"MC1R", mgn_skin_aging_r_MC1R, 4},
};
static const char *const mgn_skin_aging_refs[] = {
    "Liu et al. 2016, Curr Biol, PMID: 27189542",
};

static const char *const mgn_inflammation_profile_r_IL6[] = {
    "high",
};
static const gh_gene_match mgn_inflammation_profile_required_genes[] = {
    {"IL6", mgn_inflammation_profile_r_IL6, 1},
};
static const char *const mgn_inflammation_profile_o_SOD2[] = {
    "reduced", "high_activity",
};
static const gh_gene_match mgn_inflammation_profile_optional_genes[] = {
    {"SOD2", mgn_inflammation_profile_o_SOD2, 2},
};
static const char *const mgn_inflammation_profile_refs[] = {
    "Fishman et al. 1998, J Clin Invest",
};

const gh_narrative_pattern GH_NARRATIVES[] = {
    {
        .id = "bp_cluster",
        .title = "Your Blood Pressure Genetic Profile",
        .required_genes = mgn_bp_cluster_required_genes,
        .nrequired_genes = 2,
        .optional_genes = mgn_bp_cluster_optional_genes,
        .noptional_genes = 3,
        .min_matches = 2,
        .narrative = "You carry variants in {matched_count} genes of the renin-angiotensin-aldosterone system (RAAS), the body's primary blood pressure control pathway. Each variant independently nudges BP upward; together they compound the effect. Your AGTR1 variant overactivates the angiotensin receptor, while ACE DD increases angiotensin II production.",
        .practical = "ARBs (losartan, valsartan) target the exact receptor your AGTR1 variant overactivates. ACE inhibitors address the upstream enzyme. Sodium restriction (<2g/day) and regular aerobic exercise have outsized benefit for RAAS-pathway hypertension.",
        .references = mgn_bp_cluster_refs,
        .nreferences = 2,
    },
    {
        .id = "caffeine_profile",
        .title = "Your Caffeine Response Profile",
        .required_genes = mgn_caffeine_profile_required_genes,
        .nrequired_genes = 1,
        .optional_genes = mgn_caffeine_profile_optional_genes,
        .noptional_genes = 2,
        .min_matches = 1,
        .narrative = "Your caffeine response is shaped by {matched_count} genetic variants. CYP1A2 determines how fast you clear caffeine from your bloodstream. Slow/intermediate metabolism means caffeine lingers longer, amplifying both alertness and side effects (jitters, insomnia, anxiety).",
        .practical = "Limit to 1-2 cups before noon. Green tea provides gentler caffeine with L-theanine to smooth the curve. If you also carry COMT slow, the catecholamine amplification makes caffeine particularly stimulating.",
        .references = mgn_caffeine_profile_refs,
        .nreferences = 1,
    },
    {
        .id = "methylation_choline",
        .title = "Methylation & Choline Needs",
        .required_genes = mgn_methylation_choline_required_genes,
        .nrequired_genes = 1,
        .optional_genes = mgn_methylation_choline_optional_genes,
        .noptional_genes = 3,
        .min_matches = 1,
        .narrative = "Your methylation cycle has {matched_count} variant(s) affecting methyl donor availability and choline synthesis. PEMT creates phosphatidylcholine using SAMe \342\200\224 reduced function means higher dietary choline dependency.",
        .practical = "Prioritize choline (eggs, liver, fish) and methylfolate. If MTHFR is also reduced, SAMe production drops further, increasing PEMT's reliance on dietary choline. Slow COMT means start methyl donors at low doses.",
        .references = mgn_methylation_choline_refs,
        .nreferences = 2,
    },
    {
        .id = "iron_profile",
        .title = "Your Iron Metabolism Profile",
        .required_genes = mgn_iron_profile_required_genes,
        .nrequired_genes = 1,
        .optional_genes = NULL,
        .noptional_genes = 0,
        .min_matches = 1,
        .narrative = "You carry {matched_count} HFE variant(s) that increase intestinal iron absorption. Over decades, excess iron accumulates in the liver, heart, and pancreas. Historically, this may have been advantageous in iron-poor diets, but modern iron-fortified foods and red meat availability reverse the benefit.",
        .practical = "Monitor ferritin annually. Avoid iron supplements unless proven deficient. Regular blood donation is therapeutic and community-beneficial.",
        .references = mgn_iron_profile_refs,
        .nreferences = 1,
    },
    {
        .id = "cardiovascular_lipids",
        .title = "Your Cardiovascular Lipid Profile",
        .required_genes = mgn_cardiovascular_lipids_required_genes,
        .nrequired_genes = 1,
        .optional_genes = mgn_cardiovascular_lipids_optional_genes,
        .noptional_genes = 2,
        .min_matches = 1,
        .narrative = "Your lipid genetics include {matched_count} variant(s) influencing cholesterol transport. The CETP longevity variant promotes larger, more protective HDL particles.",
        .practical = "Your genetic lipid profile trends favorable. Support with Mediterranean diet, regular exercise, and omega-3 fatty acids.",
        .references = mgn_cardiovascular_lipids_refs,
        .nreferences = 1,
    },
    {
        .id = "vitamin_d_profile",
        .title = "Your Vitamin D Metabolism",
        .required_genes = mgn_vitamin_d_profile_required_genes,
        .nrequired_genes = 1,
        .optional_genes = mgn_vitamin_d_profile_optional_genes,
        .noptional_genes = 1,
        .min_matches = 1,
        .narrative = "Your GC variant reduces vitamin D binding protein levels, lowering circulating 25-OH vitamin D. If you also have BCMO1 reduced, beta-carotene conversion to vitamin A is impaired \342\200\224 a double hit on fat-soluble vitamin availability.",
        .practical = "Supplement D3 year-round (2,000-5,000 IU). Test 25-OH-D levels. If BCMO1 is also reduced, include preformed vitamin A sources.",
        .references = mgn_vitamin_d_profile_refs,
        .nreferences = 1,
    },
    {
        .id = "skin_aging",
        .title = "Your Skin & Sun Sensitivity Profile",
        .required_genes = mgn_skin_aging_required_genes,
        .nrequired_genes = 1,
        .optional_genes = NULL,
        .noptional_genes = 0,
        .min_matches = 1,
        .narrative = "MC1R variants reduce eumelanin (dark pigment) production, increasing UV sensitivity and photoaging. These variants are associated with looking ~2 years older and elevated melanoma risk.",
        .practical = "Daily SPF 30+ is essential. Annual dermatology screening. Topical retinoids can partially offset accelerated photoaging.",
        .references = mgn_skin_aging_refs,
        .nreferences = 1,
    },
    {
        .id = "inflammation_profile",
        .title = "Your Inflammatory Response Profile",
        .required_genes = mgn_inflammation_profile_required_genes,
        .nrequired_genes = 1,
        .optional_genes = mgn_inflammation_profile_optional_genes,
        .noptional_genes = 1,
        .min_matches = 1,
        .narrative = "IL-6 is a key inflammatory cytokine. Your variant produces higher baseline IL-6 levels, driving a more pronounced inflammatory response to triggers like poor sleep, stress, and processed foods.",
        .practical = "Anti-inflammatory diet (omega-3s, colorful vegetables, turmeric), quality sleep, and regular exercise powerfully counteract this predisposition.",
        .references = mgn_inflammation_profile_refs,
        .nreferences = 1,
    },
};
const size_t GH_NARRATIVE_COUNT = sizeof(GH_NARRATIVES) / sizeof(GH_NARRATIVES[0]);

