/* Generated by c/tools/gen_profile_data.py -- do not edit by hand.
 * Sources: the per-SNP assessors in the health profile modules.
 *
 * Each assessor branches on one allele's copy count, so every outcome
 * it can produce is captured by probing it at two, one and zero
 * copies. The aggregation that consumes these lives in gh_profiles.c.
 */

#include "gh_profiles.h"

#include <stddef.h>

static const gh_profile_marker histamine_markers[] = {
    {
        .rsid = "rs10156191",
        .gene = "AOC1 (DAO)",
        .allele = 'T',
        .outcomes = {
            {"Low DAO activity", "TT genotype -- substantially reduced diamine oxidase activity. Impaired histamine degradation in the gut.", 2, 0.0, NULL, NULL, NULL},
            {"Reduced DAO activity", "CT genotype -- moderately reduced DAO enzyme activity. Partial impairment of gut histamine clearance.", 1, 0.0, NULL, NULL, NULL},
            {"Normal DAO activity", "CC genotype -- normal diamine oxidase expression and activity.", 0, 0.0, NULL, NULL, NULL},
        },
    },
    {
        .rsid = "rs1049793",
        .gene = "AOC1 (DAO)",
        .allele = 'C',
        .outcomes = {
            {"Low DAO activity", "CC genotype -- reduced DAO enzyme stability. Combined with other DAO variants, significantly impairs histamine clearance.", 2, 0.0, NULL, NULL, NULL},
            {"Reduced DAO activity", "GC genotype -- mildly reduced DAO stability. Some impairment of histamine degradation capacity.", 1, 0.0, NULL, NULL, NULL},
            {"Normal DAO activity", "GG genotype -- normal DAO enzyme stability and function.", 0, 0.0, NULL, NULL, NULL},
        },
    },
    {
        .rsid = "rs11558538",
        .gene = "HNMT",
        .allele = 'T',
        .outcomes = {
            {"Low HNMT activity", "TT genotype -- substantially reduced histamine N-methyltransferase activity. Impaired intracellular histamine clearance.", 2, 0.0, NULL, NULL, NULL},
            {"Reduced HNMT activity", "CT genotype -- moderately reduced HNMT activity. Some impairment of intracellular histamine degradation.", 1, 0.0, NULL, NULL, NULL},
            {"Normal HNMT activity", "CC genotype -- normal HNMT enzyme function. Efficient intracellular histamine clearance.", 0, 0.0, NULL, NULL, NULL},
        },
    },
};

static const gh_profile_marker alcohol_markers[] = {
    {
        .rsid = "rs1229984",
        .gene = "ADH1B",
        .allele = 'T',
        .outcomes = {
            {"Very fast ethanol metabolism", "TT (His/His) genotype -- hyperactive ADH1B produces acetaldehyde ~40x faster. Rapid acetaldehyde buildup causes unpleasant effects and is protective against alcoholism. Common in East Asian populations (~70%).", 1, 0.0, "very_fast", NULL, NULL},
            {"Fast ethanol metabolism", "CT (Arg/His) genotype -- one hyperactive ADH1B allele. Faster-than-average ethanol-to-acetaldehyde conversion. Some protective effect against alcohol dependence.", 0, 0.0, "fast", NULL, NULL},
            {"Normal ethanol metabolism", "CC (Arg/Arg) genotype -- standard ADH1B activity. Normal rate of ethanol-to-acetaldehyde conversion. Most common in European populations (~90%).", 0, 0.0, "normal", NULL, NULL},
        },
    },
    {
        .rsid = "rs671",
        .gene = "ALDH2",
        .allele = 'A',
        .outcomes = {
            {"Very reduced acetaldehyde clearance (severe flush)", "AA (Lys/Lys) genotype -- near-complete ALDH2 deficiency. Unable to clear acetaldehyde effectively. Severe facial flushing, nausea, and tachycardia with even small amounts of alcohol. Dramatically elevated esophageal cancer risk if alcohol is consumed.", 3, 0.0, NULL, "severe", NULL},
            {"Reduced acetaldehyde clearance (mild flush)", "GA (Glu/Lys) genotype -- ~60-70% reduced ALDH2 activity. Mild to moderate facial flushing with alcohol. Significantly elevated esophageal and head/neck cancer risk if drinking despite flush. Common in ~30-40% of East Asians.", 2, 0.0, NULL, "mild", NULL},
            {"Normal acetaldehyde clearance (no flush)", "GG (Glu/Glu) genotype -- fully functional ALDH2 enzyme. Efficient acetaldehyde clearance. No genetic predisposition to alcohol flush reaction.", 0, 0.0, NULL, "none", NULL},
        },
    },
    {
        .rsid = "rs2031920",
        .gene = "CYP2E1",
        .allele = 'T',
        .outcomes = {
            {"Reduced CYP2E1 metabolism", "TT genotype -- reduced CYP2E1 transcription. Lower alternative ethanol oxidation pathway activity. May slightly reduce reactive oxygen species production from alcohol metabolism.", -1, 0.0, "reduced", NULL, NULL},
            {"Reduced CYP2E1 metabolism", "CT genotype -- mildly reduced CYP2E1 activity. Slight reduction in alternative ethanol oxidation.", 0, 0.0, "reduced", NULL, NULL},
            {"Normal CYP2E1 metabolism", "CC genotype -- standard CYP2E1 expression and activity. Normal microsomal ethanol oxidizing system.", 0, 0.0, "normal", NULL, NULL},
        },
    },
};

static const gh_profile_marker pain_markers[] = {
    {
        .rsid = "rs1799971",
        .gene = "OPRM1",
        .allele = 'G',
        .outcomes = {
            {"Significantly reduced opioid response", "GG genotype -- substantially reduced receptor expression. Markedly lower opioid efficacy; alternative pain management strategies may be needed.", 20, 0.0, NULL, NULL, NULL},
            {"Reduced opioid response", "AG genotype -- reduced mu-opioid receptor binding. May require higher opioid doses for equivalent analgesia. Also associated with reduced placebo response.", 35, 0.0, NULL, NULL, NULL},
            {"Normal opioid response", "AA genotype -- normal mu-opioid receptor expression. Standard response to opioid medications.", 50, 0.0, NULL, NULL, NULL},
        },
    },
    {
        .rsid = "rs4680",
        .gene = "COMT",
        .allele = 'A',
        .outcomes = {
            {"High pain sensitivity (Met/Met worrier)", "AA genotype -- low COMT activity, slower catecholamine clearance. Higher pain sensitivity but also higher cognitive performance under low-stress conditions.", 80, 0.0, NULL, NULL, NULL},
            {"Intermediate pain sensitivity (Val/Met)", "AG genotype -- intermediate COMT enzyme activity. Balanced pain sensitivity and stress tolerance.", 50, 0.0, NULL, NULL, NULL},
            {"Low pain sensitivity (Val/Val warrior)", "GG genotype -- high COMT activity rapidly clears catecholamines. Lower pain sensitivity, better stress resilience, but lower dopamine availability at baseline.", 25, 0.0, NULL, NULL, NULL},
        },
    },
    {
        .rsid = "rs6746030",
        .gene = "SCN9A",
        .allele = 'A',
        .outcomes = {
            {"Higher pain sensitivity", "AA genotype -- associated with increased pain perception through enhanced Nav1.7 sodium channel activity.", 80, 0.0, NULL, NULL, NULL},
            {"Intermediate pain sensitivity", "AG genotype -- one copy of the high-sensitivity allele. Mildly increased pain perception.", 60, 0.0, NULL, NULL, NULL},
            {"Normal pain sensitivity", "GG genotype -- typical Nav1.7 channel function. Standard pain signaling.", 45, 0.0, NULL, NULL, NULL},
        },
    },
    {
        .rsid = "rs8065080",
        .gene = "TRPV1",
        .allele = 'T',
        .outcomes = {
            {"Higher capsaicin sensitivity", "TT genotype -- altered TRPV1 receptor. Increased sensitivity to capsaicin, heat, and spicy foods.", 80, 0.0, NULL, NULL, NULL},
            {"Intermediate capsaicin sensitivity", "CT genotype -- one variant allele. Moderately increased capsaicin and heat sensitivity.", 55, 0.0, NULL, NULL, NULL},
            {"Normal capsaicin sensitivity", "CC genotype -- typical TRPV1 receptor function. Standard response to capsaicin and heat stimuli.", 40, 0.0, NULL, NULL, NULL},
        },
    },
};

static const gh_profile_marker thyroid_markers[] = {
    {
        .rsid = "rs965513",
        .gene = "FOXE1",
        .allele = 'A',
        .outcomes = {
            {"Higher thyroid cancer risk", "AA genotype -- strongest association with thyroid cancer susceptibility at the FOXE1/PTCSC2 locus. Regular thyroid monitoring recommended.", 0, 2.0, "cancer_risk", NULL, NULL},
            {"Moderate thyroid cancer risk", "AG genotype -- one risk allele at the FOXE1 locus. Mildly increased thyroid cancer susceptibility.", 0, 1.0, "cancer_risk", NULL, NULL},
            {"Average thyroid cancer risk", "GG genotype -- no risk alleles at the FOXE1 locus. Average population risk for thyroid cancer.", 0, 0.0, "cancer_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs2071403",
        .gene = "TPO",
        .allele = 'C',
        .outcomes = {
            {"Higher autoimmune thyroid risk", "CC genotype -- associated with increased anti-TPO antibody production. Higher susceptibility to Hashimoto's thyroiditis.", 0, 2.0, "autoimmune_risk", NULL, NULL},
            {"Moderate autoimmune thyroid risk", "CT genotype -- one risk allele for autoimmune thyroid disease. Moderate susceptibility.", 0, 1.0, "autoimmune_risk", NULL, NULL},
            {"Average autoimmune thyroid risk", "TT genotype -- no risk alleles at this TPO locus. Average risk for autoimmune thyroid disease.", 0, 0.0, "autoimmune_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs179247",
        .gene = "TSHR",
        .allele = 'A',
        .outcomes = {
            {"Higher Graves' disease susceptibility", "AA genotype -- TSH receptor variant associated with increased Graves' disease risk through altered receptor expression.", 0, 2.0, "autoimmune_risk", NULL, NULL},
            {"Moderate Graves' disease susceptibility", "AG genotype -- one risk allele for Graves' disease. Mildly increased susceptibility.", 0, 1.0, "autoimmune_risk", NULL, NULL},
            {"Average Graves' disease susceptibility", "GG genotype -- no TSHR risk alleles. Average population risk for Graves' disease.", 0, 0.0, "autoimmune_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs11206244",
        .gene = "DIO1",
        .allele = 'T',
        .outcomes = {
            {"Impaired T4-to-T3 conversion (DIO1)", "TT genotype -- reduced type 1 deiodinase activity. May have higher T4 and lower T3 levels, potentially requiring combination T4/T3 therapy.", 0, 2.0, "conversion_efficiency", NULL, NULL},
            {"Reduced T4-to-T3 conversion (DIO1)", "CT genotype -- mildly reduced DIO1 activity. Slight decrease in peripheral T4-to-T3 conversion.", 0, 1.0, "conversion_efficiency", NULL, NULL},
            {"Normal T4-to-T3 conversion (DIO1)", "CC genotype -- normal type 1 deiodinase activity. Efficient peripheral T4-to-T3 conversion.", 0, 0.0, "conversion_efficiency", NULL, NULL},
        },
    },
    {
        .rsid = "rs225014",
        .gene = "DIO2",
        .allele = 'T',
        .outcomes = {
            {"Slower T4-to-T3 conversion (DIO2 Ala/Ala)", "TT (Ala/Ala) genotype -- reduced type 2 deiodinase activity. May impair local T3 production in brain and other tissues. Some patients report better well-being on combination T4/T3.", 0, 2.0, "conversion_efficiency", NULL, NULL},
            {"Reduced T4-to-T3 conversion (DIO2 Thr/Ala)", "CT (Thr/Ala) genotype -- mildly reduced DIO2 activity. Minor impact on local T3 availability.", 0, 1.0, "conversion_efficiency", NULL, NULL},
            {"Normal T4-to-T3 conversion (DIO2 Thr/Thr)", "CC (Thr/Thr) genotype -- normal type 2 deiodinase activity. Efficient local T4-to-T3 conversion.", 0, 0.0, "conversion_efficiency", NULL, NULL},
        },
    },
};

static const gh_profile_marker hormone_markers[] = {
    {
        .rsid = "rs4646",
        .gene = "CYP19A1",
        .allele = 'T',
        .outcomes = {
            {"Higher aromatase activity", "TT genotype -- associated with higher aromatase expression and increased estrogen production from androgen precursors.", 0, 0.0, "estrogen_metabolism", "increased", NULL},
            {"Intermediate aromatase activity", "CT genotype -- intermediate aromatase activity. Normal estrogen synthesis from androgen precursors.", 0, 0.0, "estrogen_metabolism", "normal", NULL},
            {"Lower aromatase activity", "CC genotype -- associated with reduced aromatase activity. Lower rate of androgen-to-estrogen conversion.", 0, 0.0, "estrogen_metabolism", "decreased", NULL},
        },
    },
    {
        .rsid = "rs2234693",
        .gene = "ESR1",
        .allele = 'C',
        .outcomes = {
            {"Higher estrogen receptor sensitivity", "CC genotype -- associated with increased ESR1 expression and enhanced estrogen signaling. May influence bone density, cardiovascular protection, and breast tissue sensitivity.", 0, 0.0, "estrogen_metabolism", "enhanced_signaling", NULL},
            {"Intermediate estrogen receptor sensitivity", "CT genotype -- intermediate estrogen receptor expression. Typical estrogen signaling.", 0, 0.0, "estrogen_metabolism", "normal", NULL},
            {"Lower estrogen receptor sensitivity", "TT genotype -- lower ESR1 expression. May reduce estrogen-mediated effects on bone density and cardiovascular health.", 0, 0.0, "estrogen_metabolism", "reduced_signaling", NULL},
        },
    },
    {
        .rsid = "rs523349",
        .gene = "SRD5A2",
        .allele = 'G',
        .outcomes = {
            {"Higher DHT conversion", "GG (Val/Val) genotype -- normal/higher 5-alpha reductase activity. Higher DHT production from testosterone. Associated with male pattern baldness and prostate growth.", 0, 0.0, "androgen_metabolism", NULL, "increased_dht"},
            {"Intermediate DHT conversion", "GC (Val/Leu) genotype -- intermediate 5-alpha reductase activity. Moderate DHT production.", 0, 0.0, "androgen_metabolism", NULL, "normal"},
            {"Lower DHT conversion", "CC (Leu/Leu) genotype -- reduced 5-alpha reductase activity (~40% lower). Lower DHT production may reduce androgenetic alopecia and benign prostate hyperplasia risk.", 0, 0.0, "androgen_metabolism", NULL, "decreased_dht"},
        },
    },
    {
        .rsid = "rs6152",
        .gene = "AR",
        .allele = 'G',
        .outcomes = {
            {"Standard androgen receptor sensitivity", "GG genotype -- associated with typical CAG repeat length and normal androgen receptor sensitivity.", 0, 0.0, "androgen_metabolism", NULL, "normal_sensitivity"},
            {"Intermediate androgen receptor sensitivity", "AG genotype -- intermediate androgen receptor signaling based on CAG repeat proxy.", 0, 0.0, "androgen_metabolism", NULL, "intermediate_sensitivity"},
            {"Potentially altered androgen receptor sensitivity", "AA genotype -- may tag longer CAG repeats associated with reduced androgen receptor transactivation. Lower androgen sensitivity despite normal hormone levels.", 0, 0.0, "androgen_metabolism", NULL, "reduced_sensitivity"},
        },
    },
};

static const gh_profile_marker eye_markers[] = {
    {
        .rsid = "rs74315329",
        .gene = "MYOC",
        .allele = 'A',
        .outcomes = {
            {"Myocilin glaucoma variant detected", "Homozygous for MYOC Gln368Ter -- a high-penetrance glaucoma variant. Strongly associated with juvenile/early-onset primary open-angle glaucoma. Ophthalmology referral recommended.", 0, 3.0, "glaucoma_risk", NULL, NULL},
            {"Myocilin glaucoma variant detected", "Heterozygous for MYOC Gln368Ter -- a high-penetrance glaucoma variant. Strongly associated with juvenile/early-onset primary open-angle glaucoma. Ophthalmology referral recommended.", 0, 3.0, "glaucoma_risk", NULL, NULL},
            {"No MYOC glaucoma variant", "GG genotype -- no myocilin Gln368Ter variant detected. This does not rule out other glaucoma risk factors.", 0, 0.0, "glaucoma_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs4236601",
        .gene = "CAV1",
        .allele = 'A',
        .outcomes = {
            {"Higher glaucoma risk", "AA genotype -- strongest association with primary open-angle glaucoma at the CAV1/CAV2 locus. Increased intraocular pressure risk.", 0, 2.0, "glaucoma_risk", NULL, NULL},
            {"Moderate glaucoma risk", "AC genotype -- one risk allele for glaucoma at the CAV1 locus. Mildly increased susceptibility.", 0, 1.0, "glaucoma_risk", NULL, NULL},
            {"Average glaucoma risk (CAV1)", "CC genotype -- no CAV1 risk alleles. Average population risk for open-angle glaucoma at this locus.", 0, 0.0, "glaucoma_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs1048661",
        .gene = "LOXL1",
        .allele = 'G',
        .outcomes = {
            {"Higher exfoliation glaucoma risk", "GG genotype -- homozygous for LOXL1 risk allele. Significantly increased risk for exfoliation syndrome and exfoliation glaucoma, especially after age 60.", 0, 2.0, "glaucoma_risk", NULL, NULL},
            {"Moderate exfoliation glaucoma risk", "GT genotype -- one LOXL1 risk allele. Moderately increased risk for exfoliation syndrome.", 0, 1.0, "glaucoma_risk", NULL, NULL},
            {"Lower exfoliation glaucoma risk", "TT genotype -- no LOXL1 risk alleles at this position. Lower risk for exfoliation syndrome/glaucoma.", 0, 0.0, "glaucoma_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs524952",
        .gene = "GJD2",
        .allele = 'A',
        .outcomes = {
            {"Higher myopia risk (GJD2)", "AA genotype -- associated with increased myopia susceptibility. GJD2 affects retinal gap junction signaling involved in eye growth.", 0, 2.0, "myopia_risk", NULL, NULL},
            {"Moderate myopia risk (GJD2)", "AG genotype -- one risk allele for myopia at GJD2. Mildly increased susceptibility to near-sightedness.", 0, 1.0, "myopia_risk", NULL, NULL},
            {"Average myopia risk (GJD2)", "GG genotype -- no GJD2 risk alleles. Average genetic risk for myopia at this locus.", 0, 0.0, "myopia_risk", NULL, NULL},
        },
    },
    {
        .rsid = "rs8027411",
        .gene = "RASGRF1",
        .allele = 'T',
        .outcomes = {
            {"Higher myopia risk (RASGRF1)", "TT genotype -- associated with increased myopia susceptibility through altered retinal RAS/MAPK signaling and eye growth.", 0, 2.0, "myopia_risk", NULL, NULL},
            {"Moderate myopia risk (RASGRF1)", "GT genotype -- one risk allele for myopia at RASGRF1. Mildly increased near-sightedness susceptibility.", 0, 1.0, "myopia_risk", NULL, NULL},
            {"Average myopia risk (RASGRF1)", "GG genotype -- no RASGRF1 risk alleles. Average genetic myopia risk at this locus.", 0, 0.0, "myopia_risk", NULL, NULL},
        },
    },
};

const gh_profile_markers GH_HISTAMINE_MARKERS = {histamine_markers, 3};
const gh_profile_markers GH_ALCOHOL_MARKERS = {alcohol_markers, 3};
const gh_profile_markers GH_PAIN_MARKERS = {pain_markers, 4};
const gh_profile_markers GH_THYROID_MARKERS = {thyroid_markers, 5};
const gh_profile_markers GH_HORMONE_MARKERS = {hormone_markers, 4};
const gh_profile_markers GH_EYE_MARKERS = {eye_markers, 5};

