/* Generated by c/tools/gen_recommendations_data.py -- do not edit.
 * Source: genetic_health/recommendations.py
 */

#include "gh_recommendations.h"

#include <stddef.h>

static const char *const rg_blood_pressure_genes[] = {
    "ACE",
    "ADD1",
    "ADRB1",
    "AGT",
    "AGTR1",
    "GNB3",
};
static const char *const rg_blood_pressure_keywords[] = {
    "salt-sensitive",
    "hypertension",
    "blood pressure",
};
static const char *const rg_blood_pressure_actions[] = {
    "Home blood pressure monitoring (target <130/80 mmHg)",
    "Sodium intake <2,000 mg/day (DASH diet pattern)",
    "150+ min/week aerobic exercise (brisk walking, cycling, swimming)",
    "Potassium-rich foods: bananas, sweet potatoes, spinach",
    "Limit alcohol to <= 1 drink/day",
};
static const gh_monitoring_item rg_blood_pressure_monitoring[] = {
    {"Blood pressure", "Weekly (home)", "Multiple BP gene variants"},
    {"Renal function (BMP)", "Annually", "Hypertension screening"},
};

static const char *const rg_metabolic_diabetes_genes[] = {
    "CAPN10",
    "FTO",
    "IGF2BP2",
    "IRS2",
    "SOD2",
    "TCF7L2",
};
static const char *const rg_metabolic_diabetes_keywords[] = {
    "diabetes",
    "insulin",
    "glucose",
};
static const char *const rg_metabolic_diabetes_actions[] = {
    "Monitor fasting glucose and HbA1c annually",
    "Maintain healthy weight (BMI <25 or waist <94 cm men / <80 cm women)",
    "Low-glycaemic-index diet; emphasise whole grains, legumes, vegetables",
    "150+ min/week moderate exercise (improves insulin sensitivity)",
    "Consider time-restricted eating (e.g., 16:8) if appropriate",
};
static const gh_monitoring_item rg_metabolic_diabetes_monitoring[] = {
    {"Fasting glucose / HbA1c", "Annually", "Diabetes risk variants"},
    {"Lipid panel", "Annually", "Metabolic syndrome screening"},
};

static const char *const rg_lung_health_keywords[] = {
    "alpha-1 antitrypsin",
    "alpha-1-antitrypsin",
    "emphysema",
    "copd",
};
static const char *const rg_lung_health_actions[] = {
    "Absolutely avoid smoking and second-hand smoke",
    "Request AAT (alpha-1 antitrypsin) level blood test",
    "Annual spirometry to track lung function (FEV1/FVC)",
    "Minimise exposure to air pollution, dust, chemical fumes",
    "Flu and pneumonia vaccinations up to date",
};
static const gh_monitoring_item rg_lung_health_monitoring[] = {
    {"Serum AAT level", "Once (baseline)", "SERPINA1 pathogenic variant"},
    {"Spirometry (FEV1/FVC)", "Annually", "Lung function tracking"},
};

static const char *const rg_caffeine_genes[] = {
    "ADORA2A",
    "COMT",
    "CYP1A2",
};
static const char *const rg_caffeine_actions[] = {
    "Limit caffeine to <100 mg/day (1 small coffee) before 10 am",
    "Consider switching to green tea (L-theanine counterbalances jitters)",
    "Allow 10+ hours caffeine clearance before sleep",
    "Avoid caffeine entirely if experiencing anxiety or insomnia",
};

static const char *const rg_methylation_genes[] = {
    "COMT",
    "MTHFR",
    "MTRR",
    "PEMT",
};
static const char *const rg_methylation_actions[] = {
    "Methylfolate (L-5-MTHF) 400-800 mcg/day instead of folic acid",
    "Methylcobalamin (B12) 1,000 mcg sublingual",
    "Emphasise folate-rich foods: leafy greens, legumes, liver",
    "Avoid synthetic folic acid in fortified foods when possible",
    "Riboflavin (B2) 25-50 mg/day as MTHFR cofactor",
};
static const gh_monitoring_item rg_methylation_monitoring[] = {
    {"Homocysteine", "Annually", "MTHFR / methylation variants"},
    {"B12 + MMA", "Annually", "MTRR / B12 recycling"},
};

static const char *const rg_cardiovascular_genes[] = {
    "APOE",
    "CETP",
    "F2",
    "F5",
    "LRP8",
};
static const char *const rg_cardiovascular_keywords[] = {
    "myocardial infarction",
    "thrombosis",
    "thromboembolism",
    "coronary",
    "heart disease",
};
static const char *const rg_cardiovascular_actions[] = {
    "Regular lipid panel (LDL-C, apoB, Lp(a) baseline)",
    "Mediterranean diet: olive oil, fish, nuts, vegetables",
    "150+ min/week aerobic exercise",
    "Know signs of DVT/PE if clotting variants present",
    "Stay hydrated and move frequently on long flights",
};
static const gh_monitoring_item rg_cardiovascular_monitoring[] = {
    {"Lipid panel (LDL, apoB)", "Annually", "Cardiovascular risk variants"},
    {"Lp(a)", "Once (baseline)", "Independent CV risk marker"},
};

static const char *const rg_iron_genes[] = {
    "HFE",
};
static const char *const rg_iron_keywords[] = {
    "hemochromatosis",
    "iron overload",
};
static const char *const rg_iron_actions[] = {
    "Do NOT supplement iron unless deficiency is confirmed by blood test",
    "Consider regular blood donation to keep ferritin in range",
    "Moderate vitamin C intake with meals (enhances iron absorption)",
    "Annual ferritin and iron panel monitoring",
};
static const gh_monitoring_item rg_iron_monitoring[] = {
    {"Ferritin + iron panel", "Annually", "HFE variant"},
};

static const char *const rg_skin_genes[] = {
    "MC1R",
};
static const char *const rg_skin_actions[] = {
    "Daily SPF 30+ sunscreen on exposed skin (even on cloudy days)",
    "Wear protective clothing and hats during peak UV hours (10am-4pm)",
    "Annual full-body skin exam by dermatologist",
    "Topical retinoids for skin health (consult dermatologist)",
};
static const gh_monitoring_item rg_skin_monitoring[] = {
    {"Full-body skin exam", "Annually", "MC1R variant"},
};

static const char *const rg_cancer_screening_genes[] = {
    "XRCC3",
};
static const char *const rg_cancer_screening_keywords[] = {
    "cancer",
    "carcinoma",
    "malignant neoplasm",
};
static const char *const rg_cancer_screening_actions[] = {
    "Follow age-appropriate cancer screening guidelines rigorously",
    "Discuss enhanced screening schedule with oncologist if high-risk",
    "Minimise known carcinogen exposure (tobacco, excess alcohol, UV)",
    "Maintain healthy weight (obesity is a modifiable cancer risk factor)",
};
static const gh_monitoring_item rg_cancer_screening_monitoring[] = {
    {"Cancer screening (age-appropriate)", "Per guidelines", "Cancer risk signals"},
};

static const char *const rg_fitness_genes[] = {
    "ACTN3",
    "COL5A1",
    "PPARGC1A",
};
static const char *const rg_fitness_actions[] = {
    "Tailor training to your muscle fiber type (see ACTN3 result)",
    "Include both strength and endurance training regardless of genetics",
    "Pay attention to connective tissue health if COL5A1 variant present",
    "Progressive overload with adequate recovery between sessions",
};

const gh_risk_group GH_RISK_GROUPS[] = {
    {
        .id = "blood_pressure",
        .title = "Blood Pressure & Hypertension",
        .prs_condition = "hypertension",
        .genes = rg_blood_pressure_genes,
        .ngenes = 6,
        .keywords = rg_blood_pressure_keywords,
        .nkeywords = 3,
        .actions = rg_blood_pressure_actions,
        .nactions = 5,
        .doctor_note = "Multiple genetic signals converge on the renin-angiotensin-aldosterone system.  ACE inhibitors or ARBs may be especially effective given the RAAS pathway variants.  Consider earlier pharmacotherapy if lifestyle measures insufficient.",
        .monitoring = rg_blood_pressure_monitoring,
        .nmonitoring = 2,
    },
    {
        .id = "metabolic_diabetes",
        .title = "Metabolic Health & Type 2 Diabetes",
        .prs_condition = "t2d",
        .genes = rg_metabolic_diabetes_genes,
        .ngenes = 6,
        .keywords = rg_metabolic_diabetes_keywords,
        .nkeywords = 3,
        .actions = rg_metabolic_diabetes_actions,
        .nactions = 5,
        .doctor_note = "TCF7L2 risk allele impairs beta-cell insulin secretion.  Combined with additional metabolic variants and/or elevated PRS, early metformin discussion is warranted if pre-diabetic (HbA1c 5.7-6.4%).",
        .monitoring = rg_metabolic_diabetes_monitoring,
        .nmonitoring = 2,
    },
    {
        .id = "lung_health",
        .title = "Lung & Respiratory Health",
        .prs_condition = NULL,
        .genes = NULL,
        .ngenes = 0,
        .keywords = rg_lung_health_keywords,
        .nkeywords = 4,
        .actions = rg_lung_health_actions,
        .nactions = 5,
        .doctor_note = "SERPINA1 pathogenic variant detected.  Measure serum AAT level.  If low, consider referral to pulmonology for baseline assessment and monitoring plan.  Augmentation therapy may be relevant for severe deficiency.",
        .monitoring = rg_lung_health_monitoring,
        .nmonitoring = 2,
    },
    {
        .id = "caffeine",
        .title = "Caffeine Sensitivity",
        .prs_condition = NULL,
        .genes = rg_caffeine_genes,
        .ngenes = 3,
        .keywords = NULL,
        .nkeywords = 0,
        .actions = rg_caffeine_actions,
        .nactions = 4,
        .doctor_note = "Slow CYP1A2 metabolism prolongs caffeine half-life.  Combined with COMT/ADORA2A variants, caffeine may trigger anxiety and raise cardiovascular stress.  Counsel patient on caffeine reduction.",
        .monitoring = NULL,
        .nmonitoring = 0,
    },
    {
        .id = "methylation",
        .title = "Methylation & B-Vitamin Metabolism",
        .prs_condition = NULL,
        .genes = rg_methylation_genes,
        .ngenes = 4,
        .keywords = NULL,
        .nkeywords = 0,
        .actions = rg_methylation_actions,
        .nactions = 5,
        .doctor_note = "Multiple methylation cycle variants detected.  Monitor homocysteine (target <10 umol/L).  If slow COMT, start methyl donors at low dose and titrate up to avoid overmethylation symptoms.",
        .monitoring = rg_methylation_monitoring,
        .nmonitoring = 2,
    },
    {
        .id = "cardiovascular",
        .title = "Cardiovascular & Clotting Risk",
        .prs_condition = "cad",
        .genes = rg_cardiovascular_genes,
        .ngenes = 5,
        .keywords = rg_cardiovascular_keywords,
        .nkeywords = 5,
        .actions = rg_cardiovascular_actions,
        .nactions = 5,
        .doctor_note = "Convergent cardiovascular signals.  APOE e4 carriers benefit especially from exercise and saturated fat reduction.  If F5 Leiden or F2 present, discuss thromboprophylaxis for high-risk situations (surgery, immobility).",
        .monitoring = rg_cardiovascular_monitoring,
        .nmonitoring = 2,
    },
    {
        .id = "iron",
        .title = "Iron Metabolism (Hemochromatosis Risk)",
        .prs_condition = NULL,
        .genes = rg_iron_genes,
        .ngenes = 1,
        .keywords = rg_iron_keywords,
        .nkeywords = 2,
        .actions = rg_iron_actions,
        .nactions = 4,
        .doctor_note = "HFE variant detected.  Monitor ferritin and transferrin saturation.  If ferritin >300 ng/mL (men) or >200 ng/mL (women), consider therapeutic phlebotomy.  Screen family members.",
        .monitoring = rg_iron_monitoring,
        .nmonitoring = 1,
    },
    {
        .id = "skin",
        .title = "Skin & UV Protection",
        .prs_condition = NULL,
        .genes = rg_skin_genes,
        .ngenes = 1,
        .keywords = NULL,
        .nkeywords = 0,
        .actions = rg_skin_actions,
        .nactions = 4,
        .doctor_note = "MC1R variant associated with reduced melanin, increased melanoma risk, and accelerated photoaging.  Annual dermatology screening recommended.",
        .monitoring = rg_skin_monitoring,
        .nmonitoring = 1,
    },
    {
        .id = "cancer_screening",
        .title = "Cancer Screening Awareness",
        .prs_condition = "breast_cancer",
        .genes = rg_cancer_screening_genes,
        .ngenes = 1,
        .keywords = rg_cancer_screening_keywords,
        .nkeywords = 3,
        .actions = rg_cancer_screening_actions,
        .nactions = 4,
        .doctor_note = "Genetic signals suggest elevated cancer vigilance is warranted.  Consider referral to genetic counselor for comprehensive cancer risk assessment.  Enhanced screening may include earlier or more frequent imaging.",
        .monitoring = rg_cancer_screening_monitoring,
        .nmonitoring = 1,
    },
    {
        .id = "fitness",
        .title = "Fitness & Exercise Response",
        .prs_condition = NULL,
        .genes = rg_fitness_genes,
        .ngenes = 3,
        .keywords = NULL,
        .nkeywords = 0,
        .actions = rg_fitness_actions,
        .nactions = 4,
        .doctor_note = "",
        .monitoring = NULL,
        .nmonitoring = 0,
    },
};
const size_t GH_RISK_GROUP_COUNT = sizeof(GH_RISK_GROUPS) / sizeof(GH_RISK_GROUPS[0]);

static const char *const sr_pulmonologist_0_genes[] = {
    "SERPINA1",
};
static const char *const sr_pulmonologist_1_keywords[] = {
    "alpha-1 antitrypsin",
    "COPD",
    "emphysema",
};
static const gh_referral_trigger sr_pulmonologist_triggers[] = {
    {
        .source = "acmg",
        .match_any = false,
        .minimum = 0,
        .gene = NULL,
        .group = NULL,
        .min_priority = NULL,
        .genes = sr_pulmonologist_0_genes,
        .ngenes = 1,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
    {
        .source = "disease",
        .match_any = false,
        .minimum = 0,
        .gene = NULL,
        .group = NULL,
        .min_priority = NULL,
        .genes = NULL,
        .ngenes = 0,
        .keywords = sr_pulmonologist_1_keywords,
        .nkeywords = 3,
        .statuses = NULL,
        .nstatuses = 0,
    },
};

static const gh_referral_trigger sr_genetic_counselor_triggers[] = {
    {
        .source = "acmg",
        .match_any = true,
        .minimum = 0,
        .gene = NULL,
        .group = NULL,
        .min_priority = NULL,
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
    {
        .source = "pathogenic_count",
        .match_any = false,
        .minimum = 1,
        .gene = NULL,
        .group = NULL,
        .min_priority = NULL,
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
};

static const gh_referral_trigger sr_cardiologist_triggers[] = {
    {
        .source = "priority",
        .match_any = false,
        .minimum = 0,
        .gene = NULL,
        .group = "blood_pressure",
        .min_priority = "high",
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
    {
        .source = "priority",
        .match_any = false,
        .minimum = 0,
        .gene = NULL,
        .group = "cardiovascular",
        .min_priority = "high",
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
};

static const char *const sr_hematologist_0_statuses[] = {
    "carrier",
    "at_risk",
    "high_risk",
};
static const gh_referral_trigger sr_hematologist_triggers[] = {
    {
        .source = "gene_status",
        .match_any = false,
        .minimum = 0,
        .gene = "HFE",
        .group = NULL,
        .min_priority = NULL,
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = sr_hematologist_0_statuses,
        .nstatuses = 3,
    },
};

static const gh_referral_trigger sr_pharmacist_pgx_triggers[] = {
    {
        .source = "star_alleles_actionable",
        .match_any = true,
        .minimum = 0,
        .gene = NULL,
        .group = NULL,
        .min_priority = NULL,
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
};

static const gh_referral_trigger sr_dermatologist_triggers[] = {
    {
        .source = "priority",
        .match_any = false,
        .minimum = 0,
        .gene = NULL,
        .group = "skin",
        .min_priority = "low",
        .genes = NULL,
        .ngenes = 0,
        .keywords = NULL,
        .nkeywords = 0,
        .statuses = NULL,
        .nstatuses = 0,
    },
};

const gh_specialist_referral GH_SPECIALIST_REFERRALS[] = {
    {
        .id = "pulmonologist",
        .title = "Pulmonologist",
        .reason_template = "{gene}: {condition} \342\200\224 baseline pulmonary function assessment",
        .urgency = "soon",
        .triggers = sr_pulmonologist_triggers,
        .ntriggers = 2,
    },
    {
        .id = "genetic_counselor",
        .title = "Genetic Counselor",
        .reason_template = "Medically actionable genetic finding(s) detected",
        .urgency = "soon",
        .triggers = sr_genetic_counselor_triggers,
        .ntriggers = 2,
    },
    {
        .id = "cardiologist",
        .title = "Cardiologist",
        .reason_template = "Converging genetic signals in cardiovascular/BP pathways",
        .urgency = "routine",
        .triggers = sr_cardiologist_triggers,
        .ntriggers = 2,
    },
    {
        .id = "hematologist",
        .title = "Hematologist",
        .reason_template = "HFE variant \342\200\224 monitor iron studies, refer if ferritin elevated",
        .urgency = "routine",
        .triggers = sr_hematologist_triggers,
        .ntriggers = 1,
    },
    {
        .id = "pharmacist_pgx",
        .title = "Pharmacist (PGx Review)",
        .reason_template = "Actionable pharmacogenomic variants: {genes}",
        .urgency = "routine",
        .triggers = sr_pharmacist_pgx_triggers,
        .ntriggers = 1,
    },
    {
        .id = "dermatologist",
        .title = "Dermatologist",
        .reason_template = "MC1R variant \342\200\224 annual skin screening recommended",
        .urgency = "routine",
        .triggers = sr_dermatologist_triggers,
        .ntriggers = 1,
    },
};
const size_t GH_SPECIALIST_REFERRAL_COUNT = sizeof(GH_SPECIALIST_REFERRALS) / sizeof(GH_SPECIALIST_REFERRALS[0]);

