/* Generated by c/tools/gen_scorer_data.py -- do not edit by hand.
 * Sources: genetic_health/apoe.py, mt_haplogroup.py, star_alleles.py
 */

#include "gh_scorers.h"

#include <stddef.h>

const gh_apoe_risk GH_APOE_RISKS[] = {
    {"e2/e2", "reduced", 0.6, "Lowest Alzheimer's risk. May increase cardiovascular risk (type III hyperlipoproteinemia)."},
    {"e2/e3", "reduced", 0.6, "Below-average Alzheimer's risk. One protective e2 allele."},
    {"e3/e3", "average", 1, "Most common genotype (~60% of population). Average Alzheimer's risk."},
    {"e3/e4", "elevated", 2.8, "One e4 allele increases Alzheimer's risk ~2-3x. Exercise, sleep, and cardiovascular health may mitigate risk."},
    {"e2/e4", "moderate", 1.2, "Mixed: one risk allele (e4) and one protective allele (e2). Net risk near average."},
    {"e4/e4", "high", 12, "Highest genetic risk for late-onset Alzheimer's (~12x). Aggressive cardiovascular and lifestyle optimization recommended."},
};
const size_t GH_APOE_RISK_COUNT = sizeof(GH_APOE_RISKS) / sizeof(GH_APOE_RISKS[0]);

const gh_mt_marker GH_MT_TREE[] = {
    {"rs28357968", "A", "L1", "West/Central African maternal lineage (m.3666G>A)"},
    {"rs2854128", "A", "H", "Most common European maternal lineage (~40% of Europeans; m.2706A)"},
    {"rs2015062", "C", "H", "Most common European maternal lineage (~40% of Europeans; m.7028C)"},
    {"rs3928306", "A", "H1", "H1 subclade (~13% of Europeans, common in Iberia and W. Europe; m.3010G>A, also seen in J1 and D4)"},
    {"rs41456348", "C", "H5a", "H5a subclade (~2-4% of Europeans; m.4336T>C)"},
    {"rs3088309", "A", "JT", "European/Near Eastern JT lineage (~20% of Europeans; m.15452C>A)"},
    {"rs28359172", "G", "J", "European/Near Eastern lineage (~12% Europeans, associated with farming expansion; m.12612A>G)"},
    {"rs2853499", "A", "U", "Ancient European/West Asian lineage (~11% of Europeans; m.12372G>A)"},
    {"rs2853825", "A", "U5", "U5: oldest European-specific lineage (~10,000 years, Mesolithic hunter-gatherers; m.9477G>A)"},
    {"rs28358280", "G", "K", "European lineage (~10% of Europeans, Ashkenazi Jewish ~32%; m.10550A>G)"},
    {"rs28358571", "C", "K1", "K1 subclade (most K in Europe; m.1189T>C)"},
    {"rs28358587", "A", "C", "East Asian, Central Asian, and Native American maternal lineage (m.3552T>A)"},
};
const size_t GH_MT_TREE_COUNT = sizeof(GH_MT_TREE) / sizeof(GH_MT_TREE[0]);

const gh_kv GH_MT_LINEAGES[] = {
    {"L0", "African"},
    {"L1", "African"},
    {"L2", "African"},
    {"L3", "African"},
    {"M", "South/East Asian"},
    {"N", "Eurasian"},
    {"H", "European"},
    {"H1", "European"},
    {"H5a", "European"},
    {"JT", "European/Near Eastern"},
    {"J", "European/Near Eastern"},
    {"T", "European"},
    {"U", "European/West Asian"},
    {"U5", "European"},
    {"K", "European"},
    {"K1", "European"},
    {"C", "East Asian/Native American"},
    {"D", "East Asian/Native American"},
};
const size_t GH_MT_LINEAGE_COUNT = sizeof(GH_MT_LINEAGES) / sizeof(GH_MT_LINEAGES[0]);

static const gh_star_snp sa_CYP2C19__2[] = {
    {"rs4244285", "A"},
};
static const gh_star_snp sa_CYP2C19__3[] = {
    {"rs4986893", "A"},
};
static const gh_star_snp sa_CYP2C19__4[] = {
    {"rs28399504", "G"},
};
static const gh_star_snp sa_CYP2C19__5[] = {
    {"rs56337013", "T"},
};
static const gh_star_snp sa_CYP2C19__6[] = {
    {"rs72552267", "A"},
};
static const gh_star_snp sa_CYP2C19__7[] = {
    {"rs72558186", "A"},
};
static const gh_star_snp sa_CYP2C19__8[] = {
    {"rs41291556", "C"},
};
static const gh_star_snp sa_CYP2C19__17[] = {
    {"rs12248560", "T"},
};
static const gh_star_allele sa_CYP2C19_alleles[] = {
    {"*2", "no_function", sa_CYP2C19__2, 1},
    {"*3", "no_function", sa_CYP2C19__3, 1},
    {"*4", "no_function", sa_CYP2C19__4, 1},
    {"*5", "no_function", sa_CYP2C19__5, 1},
    {"*6", "no_function", sa_CYP2C19__6, 1},
    {"*7", "no_function", sa_CYP2C19__7, 1},
    {"*8", "no_function", sa_CYP2C19__8, 1},
    {"*17", "increased", sa_CYP2C19__17, 1},
};
static const char *const sa_CYP2C19_snps[] = {
    "rs4244285", "rs4986893", "rs28399504", "rs56337013", "rs72552267", "rs72558186", "rs41291556", "rs12248560",
};
static const gh_kv sa_CYP2C19_functions[] = {
    {"*1", "normal"},
    {"*2", "no_function"},
    {"*3", "no_function"},
    {"*4", "no_function"},
    {"*5", "no_function"},
    {"*6", "no_function"},
    {"*7", "no_function"},
    {"*8", "no_function"},
    {"*17", "increased"},
};

static const gh_star_snp sa_CYP2C9__2[] = {
    {"rs1799853", "T"},
};
static const gh_star_snp sa_CYP2C9__3[] = {
    {"rs1057910", "C"},
};
static const gh_star_allele sa_CYP2C9_alleles[] = {
    {"*2", "decreased", sa_CYP2C9__2, 1},
    {"*3", "decreased", sa_CYP2C9__3, 1},
};
static const char *const sa_CYP2C9_snps[] = {
    "rs1799853", "rs1057910",
};
static const gh_kv sa_CYP2C9_functions[] = {
    {"*1", "normal"},
    {"*2", "decreased"},
    {"*3", "decreased"},
};

static const gh_star_snp sa_CYP2D6__2[] = {
    {"rs16947", "A"},
};
static const gh_star_snp sa_CYP2D6__4[] = {
    {"rs3892097", "A"},
};
static const gh_star_snp sa_CYP2D6__10[] = {
    {"rs1065852", "A"},
};
static const gh_star_snp sa_CYP2D6__41[] = {
    {"rs28371725", "T"},
};
static const gh_star_allele sa_CYP2D6_alleles[] = {
    {"*2", "normal", sa_CYP2D6__2, 1},
    {"*4", "no_function", sa_CYP2D6__4, 1},
    {"*10", "decreased", sa_CYP2D6__10, 1},
    {"*41", "decreased", sa_CYP2D6__41, 1},
};
static const char *const sa_CYP2D6_snps[] = {
    "rs16947", "rs3892097", "rs1065852", "rs28371725",
};
static const gh_kv sa_CYP2D6_functions[] = {
    {"*1", "normal"},
    {"*2", "normal"},
    {"*4", "no_function"},
    {"*5", "no_function"},
    {"*6", "no_function"},
    {"*9", "decreased"},
    {"*10", "decreased"},
    {"*41", "decreased"},
};

static const gh_star_snp sa_DPYD__2A[] = {
    {"rs3918290", "A"},
};
static const gh_star_snp sa_DPYD__13[] = {
    {"rs55886062", "C"},
};
static const gh_star_allele sa_DPYD_alleles[] = {
    {"*2A", "no_function", sa_DPYD__2A, 1},
    {"*13", "decreased", sa_DPYD__13, 1},
};
static const char *const sa_DPYD_snps[] = {
    "rs3918290", "rs55886062",
};
static const gh_kv sa_DPYD_functions[] = {
    {"*1", "normal"},
    {"*2A", "no_function"},
    {"*13", "decreased"},
};

static const gh_star_snp sa_TPMT__2[] = {
    {"rs1800462", "G"},
};
static const gh_star_snp sa_TPMT__3A[] = {
    {"rs1800460", "A"},
    {"rs1142345", "C"},
};
static const gh_star_snp sa_TPMT__3B[] = {
    {"rs1800460", "A"},
};
static const gh_star_snp sa_TPMT__3C[] = {
    {"rs1142345", "C"},
};
static const gh_star_snp sa_TPMT__4[] = {
    {"rs1800584", "T"},
};
static const gh_star_allele sa_TPMT_alleles[] = {
    {"*2", "no_function", sa_TPMT__2, 1},
    {"*3A", "no_function", sa_TPMT__3A, 2},
    {"*3B", "no_function", sa_TPMT__3B, 1},
    {"*3C", "decreased", sa_TPMT__3C, 1},
    {"*4", "no_function", sa_TPMT__4, 1},
};
static const char *const sa_TPMT_snps[] = {
    "rs1800462", "rs1800460", "rs1142345", "rs1800584",
};
static const gh_kv sa_TPMT_functions[] = {
    {"*1", "normal"},
    {"*2", "no_function"},
    {"*3A", "no_function"},
    {"*3B", "no_function"},
    {"*3C", "decreased"},
    {"*4", "no_function"},
};

static const gh_star_snp sa_UGT1A1__28[] = {
    {"rs8175347", "A"},
};
static const gh_star_snp sa_UGT1A1__6[] = {
    {"rs4148323", "A"},
};
static const gh_star_allele sa_UGT1A1_alleles[] = {
    {"*28", "decreased", sa_UGT1A1__28, 1},
    {"*6", "decreased", sa_UGT1A1__6, 1},
};
static const char *const sa_UGT1A1_snps[] = {
    "rs8175347", "rs4148323",
};
static const gh_kv sa_UGT1A1_functions[] = {
    {"*1", "normal"},
    {"*28", "decreased"},
    {"*6", "decreased"},
};

static const gh_star_snp sa_NAT2__5[] = {
    {"rs1801280", "C"},
};
static const gh_star_snp sa_NAT2__6[] = {
    {"rs1799930", "A"},
};
static const gh_star_snp sa_NAT2__7[] = {
    {"rs1799931", "A"},
};
static const gh_star_snp sa_NAT2__14[] = {
    {"rs1801279", "A"},
};
static const gh_star_allele sa_NAT2_alleles[] = {
    {"*5", "decreased", sa_NAT2__5, 1},
    {"*6", "decreased", sa_NAT2__6, 1},
    {"*7", "decreased", sa_NAT2__7, 1},
    {"*14", "decreased", sa_NAT2__14, 1},
};
static const char *const sa_NAT2_snps[] = {
    "rs1801280", "rs1799930", "rs1799931", "rs1801279",
};
static const gh_kv sa_NAT2_functions[] = {
    {"*1", "normal"},
    {"*5", "decreased"},
    {"*6", "decreased"},
    {"*7", "decreased"},
    {"*14", "decreased"},
};

static const gh_star_snp sa_CYP3A5__3[] = {
    {"rs776746", "C"},
};
static const gh_star_snp sa_CYP3A5__6[] = {
    {"rs10264272", "T"},
};
static const gh_star_allele sa_CYP3A5_alleles[] = {
    {"*3", "no_function", sa_CYP3A5__3, 1},
    {"*6", "no_function", sa_CYP3A5__6, 1},
};
static const char *const sa_CYP3A5_snps[] = {
    "rs776746", "rs10264272",
};
static const gh_kv sa_CYP3A5_functions[] = {
    {"*1", "normal"},
    {"*3", "no_function"},
    {"*6", "no_function"},
    {"*7", "no_function"},
};

static const gh_star_snp sa_CYP3A4__22[] = {
    {"rs35599367", "A"},
};
static const gh_star_allele sa_CYP3A4_alleles[] = {
    {"*22", "decreased", sa_CYP3A4__22, 1},
};
static const char *const sa_CYP3A4_snps[] = {
    "rs35599367",
};
static const gh_kv sa_CYP3A4_functions[] = {
    {"*1", "normal"},
    {"*22", "decreased"},
    {"*20", "no_function"},
};

static const gh_star_snp sa_CYP1A2__1F[] = {
    {"rs762551", "A"},
};
static const gh_star_snp sa_CYP1A2__1C[] = {
    {"rs2069514", "A"},
};
static const gh_star_snp sa_CYP1A2__1K[] = {
    {"rs12720461", "T"},
};
static const gh_star_allele sa_CYP1A2_alleles[] = {
    {"*1F", "increased", sa_CYP1A2__1F, 1},
    {"*1C", "decreased", sa_CYP1A2__1C, 1},
    {"*1K", "decreased", sa_CYP1A2__1K, 1},
};
static const char *const sa_CYP1A2_snps[] = {
    "rs762551", "rs2069514", "rs12720461",
};
static const gh_kv sa_CYP1A2_functions[] = {
    {"*1", "normal"},
    {"*1F", "increased"},
    {"*1C", "decreased"},
    {"*1K", "decreased"},
};

static const gh_star_snp sa_SLCO1B1__5[] = {
    {"rs4149056", "C"},
};
static const gh_star_snp sa_SLCO1B1__15[] = {
    {"rs4149056", "C"},
    {"rs2306283", "G"},
};
static const gh_star_snp sa_SLCO1B1__17[] = {
    {"rs2306283", "G"},
};
static const gh_star_allele sa_SLCO1B1_alleles[] = {
    {"*5", "decreased", sa_SLCO1B1__5, 1},
    {"*15", "decreased", sa_SLCO1B1__15, 2},
    {"*17", "decreased", sa_SLCO1B1__17, 1},
};
static const char *const sa_SLCO1B1_snps[] = {
    "rs4149056", "rs2306283",
};
static const gh_kv sa_SLCO1B1_functions[] = {
    {"*1", "normal"},
    {"*5", "decreased"},
    {"*15", "decreased"},
    {"*17", "decreased"},
};

const gh_star_gene GH_STAR_GENES[] = {
    {
        .gene = "CYP2C19",
        .alleles = sa_CYP2C19_alleles,
        .nalleles = 8,
        .snps = sa_CYP2C19_snps,
        .nsnps = 8,
        .functions = sa_CYP2C19_functions,
        .nfunctions = 9,
        .clinical_note = NULL,
    },
    {
        .gene = "CYP2C9",
        .alleles = sa_CYP2C9_alleles,
        .nalleles = 2,
        .snps = sa_CYP2C9_snps,
        .nsnps = 2,
        .functions = sa_CYP2C9_functions,
        .nfunctions = 3,
        .clinical_note = NULL,
    },
    {
        .gene = "CYP2D6",
        .alleles = sa_CYP2D6_alleles,
        .nalleles = 4,
        .snps = sa_CYP2D6_snps,
        .nsnps = 4,
        .functions = sa_CYP2D6_functions,
        .nfunctions = 8,
        .clinical_note = "23andMe cannot detect CYP2D6 gene deletions (*5) or duplications (*1xN/*2xN). Copy number variants account for ~20-30% of poor/ultrarapid metabolizers. This result may underestimate phenotype severity.",
    },
    {
        .gene = "DPYD",
        .alleles = sa_DPYD_alleles,
        .nalleles = 2,
        .snps = sa_DPYD_snps,
        .nsnps = 2,
        .functions = sa_DPYD_functions,
        .nfunctions = 3,
        .clinical_note = "DPYD deficiency can cause fatal 5-FU/capecitabine toxicity. Pre-treatment testing recommended.",
    },
    {
        .gene = "TPMT",
        .alleles = sa_TPMT_alleles,
        .nalleles = 5,
        .snps = sa_TPMT_snps,
        .nsnps = 4,
        .functions = sa_TPMT_functions,
        .nfunctions = 6,
        .clinical_note = "TPMT deficiency can cause life-threatening myelosuppression with azathioprine/6-MP.",
    },
    {
        .gene = "UGT1A1",
        .alleles = sa_UGT1A1_alleles,
        .nalleles = 2,
        .snps = sa_UGT1A1_snps,
        .nsnps = 2,
        .functions = sa_UGT1A1_functions,
        .nfunctions = 3,
        .clinical_note = "UGT1A1*28 causes Gilbert syndrome and irinotecan toxicity. UGT1A1*6 common in East Asian populations.",
    },
    {
        .gene = "NAT2",
        .alleles = sa_NAT2_alleles,
        .nalleles = 4,
        .snps = sa_NAT2_snps,
        .nsnps = 4,
        .functions = sa_NAT2_functions,
        .nfunctions = 5,
        .clinical_note = "NAT2 acetylator status affects isoniazid (TB treatment), sulfonamides, hydralazine, and procainamide. Slow acetylators (~50% of Europeans) are at higher risk of drug-induced lupus and peripheral neuropathy from isoniazid.",
    },
    {
        .gene = "CYP3A5",
        .alleles = sa_CYP3A5_alleles,
        .nalleles = 2,
        .snps = sa_CYP3A5_snps,
        .nsnps = 2,
        .functions = sa_CYP3A5_functions,
        .nfunctions = 4,
        .clinical_note = "CYP3A5 metabolizes tacrolimus, cyclosporine, and some statins. *1 allele (expresser) is common in Africans (~70%) but rare in Europeans (~6%). Non-expressers (*3/*3) may need lower tacrolimus doses.",
    },
    {
        .gene = "CYP3A4",
        .alleles = sa_CYP3A4_alleles,
        .nalleles = 1,
        .snps = sa_CYP3A4_snps,
        .nsnps = 1,
        .functions = sa_CYP3A4_functions,
        .nfunctions = 3,
        .clinical_note = "CYP3A4 metabolizes ~30% of all drugs including statins, calcium channel blockers, macrolide antibiotics, opioids, and many chemotherapeutics. *22 (decreased function) affects ~5% of Europeans and may require dose reductions for sensitive substrates.",
    },
    {
        .gene = "CYP1A2",
        .alleles = sa_CYP1A2_alleles,
        .nalleles = 3,
        .snps = sa_CYP1A2_snps,
        .nsnps = 3,
        .functions = sa_CYP1A2_functions,
        .nfunctions = 4,
        .clinical_note = "CYP1A2 metabolizes caffeine, theophylline, melatonin, and fluvoxamine. *1F (rapid) is the most common inducible allele. Slow metabolizers should limit caffeine to mornings and may need lower doses of theophylline.",
    },
    {
        .gene = "SLCO1B1",
        .alleles = sa_SLCO1B1_alleles,
        .nalleles = 3,
        .snps = sa_SLCO1B1_snps,
        .nsnps = 2,
        .functions = sa_SLCO1B1_functions,
        .nfunctions = 4,
        .clinical_note = "SLCO1B1 encodes the hepatic statin transporter OATP1B1. *5 (rs4149056 TC/CC) increases simvastatin myopathy risk 5-17x. CPIC recommends avoiding simvastatin >20mg or switching to rosuvastatin/pravastatin for *5 carriers.",
    },
};
const size_t GH_STAR_GENE_COUNT = sizeof(GH_STAR_GENES) / sizeof(GH_STAR_GENES[0]);

const gh_phenotype_rule GH_PHENOTYPE_RULES[] = {
    {"increased", "increased", "ultrarapid"},
    {"increased", "normal", "rapid"},
    {"normal", "normal", "normal"},
    {"decreased", "normal", "intermediate"},
    {"decreased", "increased", "normal"},
    {"decreased", "decreased", "intermediate"},
    {"increased", "no_function", "intermediate"},
    {"no_function", "normal", "intermediate"},
    {"decreased", "no_function", "poor"},
    {"no_function", "no_function", "poor"},
};
const size_t GH_PHENOTYPE_RULE_COUNT = sizeof(GH_PHENOTYPE_RULES) / sizeof(GH_PHENOTYPE_RULES[0]);

