/* Generated by c/tools/gen_traits_data.py -- do not edit by hand.
 * Source: genetic_health/traits.py
 *
 * Outcomes are recorded by running each Python predictor against a
 * genome built to reach that branch, so the wording stays identical.
 */

#include "gh_traits.h"

#include <stddef.h>

static const gh_trait_outcome t_earwax_type[] = {
    {"Unknown", "low", "ABCC11 SNP not available."},
    {"Dry earwax", "high", "TT genotype \342\200\224 dry, flaky earwax. Common in East Asian populations (~80-95%). Also associated with reduced body odor."},
    {"Wet earwax", "high", "CT genotype \342\200\224 wet earwax (C is dominant). One copy of the dry earwax allele."},
    {"Wet earwax", "high", "CC genotype \342\200\224 wet, sticky earwax. Most common in European and African populations."},
};

static const gh_trait_outcome t_lactose_tolerance[] = {
    {"Unknown", "low", "Lactase persistence SNP (rs4988235) not available."},
    {"Lactose tolerant", "high", "AA genotype \342\200\224 you produce lactase into adulthood. Dairy digestion is normal. Common in Northern European descent."},
    {"Likely lactose tolerant", "moderate", "AG genotype \342\200\224 one copy of the lactase persistence allele. Most people with this genotype tolerate dairy well."},
    {"Likely lactose intolerant", "high", "GG genotype \342\200\224 lactase production typically declines after childhood. You may experience bloating, gas, or diarrhea from dairy. Common in East Asian, African, and Southern European populations."},
};

static const gh_trait_outcome t_cilantro_taste[] = {
    {"Unknown", "low", "OR6A2 SNP not available for cilantro taste prediction."},
    {"Likely perceives cilantro as soapy", "moderate", "CC genotype at OR6A2 \342\200\224 associated with detecting aldehyde compounds in cilantro that taste soapy or unpleasant. ~15% of people of European descent report this."},
    {"Possible mild cilantro aversion", "low", "CT genotype \342\200\224 one copy of the aversion allele. Some people with this genotype notice a slight soapy taste; others do not."},
    {"Normal cilantro taste (no soapy perception)", "moderate", "TT genotype \342\200\224 no OR6A2 aversion allele. Cilantro likely tastes herbal and pleasant to you."},
};

static const gh_trait_outcome t_asparagus_smell[] = {
    {"Unknown", "low", "rs4481887 not available for asparagus smell prediction."},
    {"Likely can smell asparagus metabolites", "moderate", "GG genotype \342\200\224 associated with ability to detect the characteristic smell of asparagus in urine. Almost everyone produces the metabolites, but not everyone can smell them."},
    {"May partially detect asparagus smell", "low", "GA genotype \342\200\224 intermediate ability to detect asparagus metabolites in urine."},
    {"Likely cannot smell asparagus metabolites", "moderate", "AA genotype \342\200\224 associated with asparagus anosmia (inability to smell asparagus metabolites). ~40% of people have this."},
};

static const gh_trait_outcome t_muscle_fiber_type[] = {
    {"Unknown", "low", "ACTN3 SNP (rs1815739) not available."},
    {"Endurance oriented (XX)", "high", "TT (XX) genotype \342\200\224 no alpha-actinin-3 in fast-twitch fibers. Associated with endurance performance and better muscle recovery. ~18% of Europeans, ~25% of Asians."},
    {"Mixed power/endurance (RX)", "moderate", "CT (RX) genotype \342\200\224 intermediate fast-twitch fiber composition. Versatile athletic profile suitable for both power and endurance activities."},
    {"Power/sprint oriented (RR)", "high", "CC (RR) genotype \342\200\224 full alpha-actinin-3 expression in fast-twitch muscle fibers. Found in ~97% of Olympic sprinters. Favors explosive power sports."},
};

static const gh_trait_outcome t_secretor_status[] = {
    {"Unknown", "low", "FUT2 SNP (rs601338) not available."},
    {"Non-secretor", "high", "AA genotype \342\200\224 non-secretor. You don't secrete ABO blood group antigens in saliva/mucus. Higher B12 deficiency risk but resistant to norovirus. Altered gut microbiome composition (~20% of Europeans)."},
    {"Secretor (carrier)", "high", "GA genotype \342\200\224 secretor (one non-secretor allele). Normal ABO antigen secretion. Carrier of non-secretor variant."},
    {"Secretor", "high", "GG genotype \342\200\224 secretor. Normal ABO antigen secretion in saliva and mucus. Typical gut microbiome composition."},
};

static const gh_trait_outcome t_photic_sneeze[] = {
    {"Unknown", "low", "Photic sneeze SNP not available."},
    {"Likely sun sneezer", "moderate", "CC genotype \342\200\224 associated with the photic sneeze reflex (ACHOO syndrome). Bright light triggers sneezing. Affects ~25% of people."},
    {"Likely sun sneezer", "moderate", "CT genotype \342\200\224 associated with the photic sneeze reflex (ACHOO syndrome). Bright light triggers sneezing. Affects ~25% of people."},
    {"Unlikely sun sneezer", "moderate", "TT genotype \342\200\224 not associated with photic sneeze reflex. Bright light unlikely to trigger sneezing."},
};

static const gh_trait_outcome t_hair_curl[] = {
    {"Unknown", "low", "TCHH hair texture SNP not available."},
    {"Likely straight hair", "moderate", "AA genotype \342\200\224 associated with straighter hair texture. Hair curliness is polygenic; this is one contributor."},
    {"Intermediate hair texture", "low", "AT genotype \342\200\224 intermediate effect on hair curliness."},
    {"Likely wavy or curly hair", "moderate", "TT genotype \342\200\224 associated with curlier hair texture in Europeans. Many other genes also contribute."},
};

static const gh_trait_outcome t_baldness_risk[] = {
    {"Unknown", "low", "Baldness susceptibility SNP not available."},
    {"Higher baldness risk", "moderate", "CC genotype \342\200\224 associated with increased risk of androgenetic alopecia (male pattern baldness). This is one of many contributing loci; AR/Xq12 is a stronger predictor."},
    {"Average baldness risk", "low", "CT genotype \342\200\224 average genetic susceptibility to male pattern baldness at this locus."},
    {"Lower baldness risk", "moderate", "TT genotype \342\200\224 lower genetic susceptibility to male pattern baldness at this locus. Other genes still contribute."},
};

static const gh_trait_outcome t_unibrow_tendency[] = {
    {"Unknown", "low", "PAX3 eyebrow SNP not available."},
    {"Higher unibrow tendency", "moderate", "CC genotype at PAX3 \342\200\224 associated with thicker eyebrow growth and higher tendency for connected eyebrows (synophrys). Found in GWAS of facial hair traits."},
    {"Average eyebrow connectivity", "low", "CT genotype \342\200\224 intermediate effect on eyebrow connectivity."},
    {"Lower unibrow tendency", "moderate", "TT genotype \342\200\224 associated with more separated eyebrows and finer brow hair."},
};

const gh_simple_trait GH_SIMPLE_TRAITS[] = {
    {"earwax_type", "rs17822931", "ABCC11", 'T', t_earwax_type},
    {"lactose_tolerance", "rs4988235", "MCM6/LCT", 'A', t_lactose_tolerance},
    {"cilantro_taste", "rs72921001", "OR6A2", 'C', t_cilantro_taste},
    {"asparagus_smell", "rs4481887", "near OR2M7", 'G', t_asparagus_smell},
    {"muscle_fiber_type", "rs1815739", "ACTN3 R577X", 'T', t_muscle_fiber_type},
    {"secretor_status", "rs601338", "FUT2", 'A', t_secretor_status},
    {"photic_sneeze", "rs10427255", "near ZEB2", 'C', t_photic_sneeze},
    {"hair_curl", "rs11803731", "TCHH", 'A', t_hair_curl},
    {"baldness_risk", "rs2180439", "20p11", 'C', t_baldness_risk},
    {"unibrow_tendency", "rs12651896", "PAX3", 'C', t_unibrow_tendency},
};
const size_t GH_SIMPLE_TRAIT_COUNT = sizeof(GH_SIMPLE_TRAITS) / sizeof(GH_SIMPLE_TRAITS[0]);

const gh_trait_outcome GH_EYE_COLOR_OUTCOMES[] = {
    /* unknown */
    {"Unknown", "low", "Primary eye color SNP (rs12913832) not available."},
    /* blue_oca2 */
    {"Blue or green", "moderate", "HERC2 AA predicts blue, but OCA2 variant shifts toward green/hazel."},
    /* blue */
    {"Likely blue", "high", "HERC2 AA is the strongest predictor of blue eyes (~70-80% accuracy)."},
    /* het_oca2 */
    {"Green or hazel", "moderate", "Heterozygous HERC2 with OCA2 variant favors green/hazel."},
    /* het */
    {"Green, hazel, or light brown", "moderate", "Heterozygous HERC2 \342\200\224 intermediate pigmentation. Most commonly green or hazel."},
    /* brown */
    {"Likely brown", "high", "HERC2 GG is strongly associated with brown eyes (~90% in most populations)."},
};

const gh_trait_outcome GH_HAIR_COLOR_OUTCOMES[] = {
    /* unknown */
    {"Unknown", "low", "MC1R SNPs not available for hair color prediction."},
    /* red */
    {"Likely red or auburn", "high", "Two or more MC1R loss-of-function alleles strongly predict red hair."},
    /* one_variant */
    {"Possible red tint or auburn highlights", "moderate", "One MC1R variant \342\200\224 may have red highlights, strawberry blonde, or be a carrier without visible effect."},
    /* none */
    {"Non-red (blonde, brown, or black \342\200\224 not determinable from MC1R alone)", "low", "No MC1R red hair variants detected. Hair color depends on many other genes."},
};

const gh_trait_outcome GH_FRECKLING_OUTCOMES[] = {
    /* unknown */
    {"Unknown", "low", "MC1R SNPs not available for sun sensitivity prediction."},
    /* high */
    {"High freckling tendency, increased sun sensitivity", "high", "Multiple MC1R variants \342\200\224 higher UV sensitivity, increased freckling, and elevated skin cancer risk. Daily SPF recommended."},
    /* moderate */
    {"Moderate freckling tendency", "moderate", "One MC1R variant \342\200\224 mildly increased sun sensitivity and freckling tendency."},
    /* typical */
    {"Typical sun sensitivity", "moderate", "No MC1R risk variants \342\200\224 typical melanin production. Sun protection still recommended."},
};

const gh_trait_outcome GH_BITTER_TASTE_OUTCOMES[] = {
    /* unknown */
    {"Unknown", "low", "TAS2R38 SNPs not available for bitter taste prediction."},
    /* supertaster */
    {"Strong bitter taster (supertaster)", "high", "PAV/PAV haplotype \342\200\224 you strongly taste bitter compounds like PTC and PROP. Broccoli, Brussels sprouts, and dark coffee may taste more bitter to you."},
    /* medium */
    {"Medium bitter taster", "moderate", "PAV/AVI haplotype \342\200\224 you have intermediate bitter taste sensitivity. Most bitter foods are noticeable but not overwhelming."},
    /* non_taster */
    {"Non-taster (low bitter sensitivity)", "high", "AVI/AVI haplotype \342\200\224 you have low sensitivity to bitter compounds. You may enjoy bitter vegetables and black coffee more than average."},
};

const char *const GH_TRAIT_ORDER[] = {
    "eye_color",
    "hair_color",
    "earwax_type",
    "freckling",
    "lactose_tolerance",
    "bitter_taste",
    "cilantro_taste",
    "asparagus_smell",
    "muscle_fiber_type",
    "secretor_status",
    "photic_sneeze",
    "hair_curl",
    "baldness_risk",
    "unibrow_tendency",
    NULL,
};

const gh_kv GH_TRAIT_SNP_LABELS[] = {
    {"rs12913832", "HERC2"},
    {"rs1800407", "OCA2"},
    {"rs1805007", "MC1R R151C"},
    {"rs1805008", "MC1R R160W"},
    {"rs713598", "TAS2R38 A49P"},
    {"rs1726866", "TAS2R38 V262A"},
    {"rs10246939", "TAS2R38 I296V"},
};
const size_t GH_TRAIT_SNP_LABEL_COUNT = sizeof(GH_TRAIT_SNP_LABELS) / sizeof(GH_TRAIT_SNP_LABELS[0]);

